### ISSUE TITLE
Dates are being written as YYYY-M-D, not YYYY-MM-DD

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/traceability-vocab#101]
`YYYY-M-D` dates may be acceptable in many places (where they are treated as if there were a leading `0` on the `M` and `D` values), but they're still *troublesome* in many of those places.

I suggest *not* using `YYYY-M-D` anywhere *unless it's explicitly as test fodder, to prove some functionality and/or breakage.*

**Comment by mprorock** [comment]
damn, i wish there was a better upvote.  let me see if there is a way to regex or pattern check for this on lint and error

**Comment by TallTed** [comment]
I don't know which flavor of regex applies here... 

`####-#-#` might find what's needed. 

Or `[0-9][0-9][0-9][0-9]-[0-9]-[0-9]`.

**Comment by mprorock** [comment]
closing this issue - this is now covered in docs, and past, present, and future, correctly formatted dates are available in the data utils
