### ISSUE TITLE
npm i does not update eslint and eslint-airbnb packages

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [w3c-ccg/traceability-vocab#131]
@OR13 @mprorock @mkhraisha ... i just updated my repo with the latest and greatest after Orie's monster PR. What I noticed is that (at least on windows) `npm i` did not update `eslint` in `root` and `packages/traceability-schemas`. that should happen automatically with npm i

**Comment by Therecanbeonlyone1969** [comment]
@OR13 you updated that, right? At least I think I saw that in your last PR

**Comment by mprorock** [comment]
I put a bunch of changes in that should be helping with overall build and verify process

**Comment by mprorock** [comment]
I believe this is resolved now in #136
