### ISSUE TITLE
add windows as supported OS

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [w3c-ccg/traceability-vocab#132]
@OR13 @mprorock @mkhraisha ... I need to run everything in git bash since commands such as `rm` are not supported on Windows machines natively. I think it might be worth adding windows support in CI

**Comment by mprorock** [comment]
do you have WSL version 1 or 2 ?

**Comment by Therecanbeonlyone1969** [comment]
@mprorock ... never answered. sorry. I do not run Linux on windows10.  I think what we can do is to add a windows10 section in the readme.md with instructions to install node.js and gitbash and be off to the races or install wsl 2 and a linux distribution and then follow the rest of the readme. I think that is the most straightforward path. Happy to write those windows instructions and do a PR. Thoughts? cc @OR13 @bumblefudge

**Comment by bumblefudge** [comment]
Hey sorry just saw this. I would say, yes plz, add a Windows 10 section, I can test the regular section on WSL2 and add annotations if anything needs an additional flag or $PATH concat or whatever

**Comment by mkhraisha** [comment]
I have tested this on WSL2 and there are no issues that I ran into.

**Comment by OR13** [comment]
we should close this issue.

**Comment by OR13** [comment]
believe this issue was resolved.
