### ISSUE TITLE
Entry Number MUST match CATAIR

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#14]
alpha numeric / filer code / entry number + check digit

**Comment by mprorock** [comment]
my inclination is to close this issue - while i agree with the statement around CATAIR i think business logic likely should be external to this project.  If there are certain core requirements that we want to enforce for data that utilizes this vocabulary that should be a separate policy / profile discussion and accompanying test suite.  perhaps a good candidate for a future plugfest?

**Comment by OR13** [comment]
yes, closing... we have been directed to make the API a best in class HTTP JSON api, and not bound by character / field limits, such as are described n CATAIR.
