### ISSUE TITLE
Consider Estimated Date of Arrival

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#15]
Need to add some sections regarding shipping / arrival data modeling.

**Comment by mprorock** [comment]
do you want this on data structures/schema's themselves, or more documentation / example minded?  This is certainly something that we are starting to account for.

**Comment by OR13** [comment]
@mprorock I think we need a more generic temporal data model for physical items and documents.... This was originally opened on a call regarding linking to entry documentation. Obviously we want to be as generic as we can wrt customs processes in other countries... I think we can close this, when we have some term definitions that account for it that can be linked to the issue.

**Comment by mprorock** [comment]
@OR13 added an example that touches on this subject in pr #70

**Comment by OR13** [comment]
thanks, looks like we got this in.

**Comment by TallTed** [comment]
Remove "Help wanted" since it's done?
