### ISSUE TITLE
Document meeting process in README

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#151]
Add instructions from the CCG mailing list on how to run meetings to the README.

https://meet.w3c-ccg.org/traceability

The bot will show up in the main #ccg IRC channel. Make sure to select "Start
Recording" at the beginning of the call and "Stop Recording" when you're done.
Make sure to kick everyone out of the room when the meeting is done. Once the
last person leaves, everything else is automated (publishing raw IRC log,
audio, and video). If you want to clean up the minutes, it takes about 5-10
minutes to clean up the transcription and publish it.

I will need to add Orie and MikeP as admins so they can start meetings. I'll
send you those login details over a secure medium. Is there anyone else that
should have rights to start and run those meetings?

**Comment by vsnt** [comment]
FYI, here's instructions on creating minutes from the github interface for those who don't want to download meeting files from 2014. https://docs.google.com/document/d/1xsFZ6GKOHLsYwIN8DGYnVZRtxvx9eVZ4QQ6WJF6zgcI/edit

**Comment by vsnt** [comment]
This is off the top of my head, which means it can be better codified.

1. Send meeting agenda (ideally as early as possible several days in advance, template below)
2. Log into text chat: http://irc.w3.org/?channels=ccg / irc://irc.w3.org:6665/#ccg
3. Log into Jitsi: https://meet.w3c-ccg.org/traceability
4. You should see ccgbot which logs between the jitsi chat and IRC chat.
5. Make sure you are logged in as host (click on your icon and log-in - jitsi doesn't always automagically log you in)
6. Say a little intro, then decide to start the recording
7. Start the recording by clicking on the three dots, select "start recording." If you don't see this, you are not logged in as an admin. There will be a brief pause and then the VOICE OF RECORDING NOTIFICATION will boom through the room.
8. Run your meeting.
9. At the end of the meeting, turn off recording (same three dots, select "Stop recording.") VOICE OF STOP RECORDING will boom through the room.
10. Kick everyone out of the room at the end, so CCG bot knows to shut down.
11. Now you can go do minutes. Or procrastinate not doing them.

**Comment by vsnt** [comment]
Meeting Agenda template, but just use what works best for you. Prolly want to make sure to include the IPR note & directions to join the CCG.

Meeting Date: + bonus link to updated date/time (e.g. https://www.timeanddate.com/worldclock/converter.html?iso=20210427T160000&p1=tz_pt&p2=tz_et&p3=tz_cet)

Text Chat:
      http://irc.w3.org/?channels=ccg
      irc://irc.w3.org:6665/#ccg

Jitsi: https://meet.w3c-ccg.org/traceability

Minutes: https://w3c-ccg.github.io/meetings/ (link directly to previous minutes for bonus operator points)

1. Agenda Review (2 minutes)

2. IP Note: (1 minute)
Anyone can participate in these calls. However, all substantive contributors to any CCG Work Items must be members of the CCG with full IPR agreements signed. https://www.w3.org/community/credentials/join
a. Ensure you have a W3 account: https://www.w3.org/accounts/request
b. W3C COMMUNITY CONTRIBUTOR LICENSE AGREEMENT (CLA): https://www.w3.org/community/about/agreements/cla/

3. Call Notes
a. These minutes and an audio recording of everything said on this call are archived at https://w3c-ccg.github.io/meetings/
b. We use IRC to queue speakers during the call as well as to take minutes. http://irc.w3.org/?channels=ccg or http://irc.w3.org:6665/#ccg or the Jitsi text chat.
c. All attendees should type “present+” to get your name on the attendee list in the transcript.
d. In IRC type “q+” to add yourself to the queue, with an optional reminder, e.g., “q+ to mention something”. The “to” is required.
e. If you’re not on IRC, simply ask to be put on the queue.
4. Scribe Selection
5. Meat of the meeting

**Comment by OR13** [comment]
@bumblefudge thanks for the PR!

**Comment by OR13** [comment]
this done!
