### ISSUE TITLE
project needs a rename, or planned output needs generalization beyond supply chain

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/traceability-vocab#153]
[The repo homepage](https://github.com/w3c-ccg/traceability-vocab/) says this vocab is for "supply-chain traceability", but it's named simply, `traceability-vocab`, implying it's meant to be far more general-purpose.

As was said in today's CCG call, it seems clear that there will be other "traceability vocabs" (plural!) following.

It seems equally clear that none of these should be generically named "traceability vocab", and *this* one should perhaps be named "supply-chain traceability vocab" or similar, sooner than later.  (I might suggest "supply-chain provenance vocab", as it has become more clear that that is what is being built here ... and I still wonder whether any effort was made at trying to put PROV-O to use.)

If the needs are around _verifiability_ of supply-chain provenance statements, and _security_ of transmission of such statements, and methods/means of such _transmission_, including verifiability of provenance of those statements (to whatever depth such may be needed, along the way from wilderness to harvested/gathered/mined/etc. raw material to finished product), then PROV-O is an even more useful tool -- and will save much time and energy along the way -- as will Verifiable Credentials, among other already-produced-works -- rather than re-inventing another wheel, as currently appears to be the project at hand.

**Comment by OR13** [comment]
> This specification describes a Linked Data vocabulary for asserting Verifiable Credentials related to traceability information, such as chemical properties, mechanical properties, country of origin, and other attributes used to determine the status of a products and materials in a supply chain.

The work item was created specifically to address supply chain... and its not the first vocabulary to do so:

Today, we already rely on other ontologies, like:

- [schema.org](http://schema.org/)
- [gs1 web vocab](https://www.gs1.org/voc/)
- [chebi](https://www.ebi.ac.uk/chebi/)

We probably could use more coverage for software supply chain use cases...


No reason we couldn't add examples for:

- https://www.w3.org/TR/trace-context/
- https://www.w3.org/TR/ldp/
- https://www.w3.org/TR/odrl-model/
- https://www.w3.org/TR/prov-o/

PRs are welcome, but suggesting the work item be renamed is not constructive imo... have a look at how GS1 frames their traceability work:


> ... traceability solutions provide the best path to interoperability, protect companies' investments and scale up. Greater levels of digitalisation, speed and data accuracy become possible. Each trading partner in the chain becomes free to choose the solution on the market that best meets its specific needs.

- https://www.gs1.org/standards/traceability


I think this is what the companies who have been contributing to the work item are focused on achieving.

**Comment by OR13** [comment]
Other work items with a similar structure:

- https://w3id.org/citizenship/v1
- https://w3id.org/vaccination/v1

**Comment by mprorock** [comment]
I think @OR13 hit the nail on the head - we have started with defining properties related to supply chain traceability use cases, but this can also serve as a broader repo for traceability in general that helps to bring in other vocabs as needed such that they can be used with verifiable credentials and JSON-LD where they do not currently support that model.   Happy to take PRs from folks with other subject matter backgrounds.

**Comment by bumblefudge** [comment]
The first round of work on this vocabulary was focused on cross-border commodity traceability, and the E-Commerce terms added were cross-border product/package tracing.  I would rather accept PRs from other traceability use cases (software supply chain and dataset traceability for ML purposes are two that come to mind) than foreclose those contributions in advance-- especially if those PRs come *first* as use-cases and are discussed on public calls now that we're holding them!

**Comment by mprorock** [comment]
> dataset traceability for ML purposes

excellent call out as we are currently in discussion on what aspects of our internal training/test dataset and modeling traceability we can release in an open source manner

**Comment by OR13** [comment]
I do see a chance we might split the contexts in the future: https://github.com/transmute-industries/ns.did.ai/tree/master/suites

so that similar to did core, you could assemble just the contexts you needed instead of taking a kitchen sink.

something like:

```
"@context": [
     "https://www.w3.org/2018/credentials/v1",
     "https://w3id.org/traceability/v1",
     "https://w3id.org/traceability/agriculture/v1",
  ],
```

or 

```
"@context": [
     "https://www.w3.org/2018/credentials/v1",
     "https://w3id.org/traceability/v1",
     "https://w3id.org/traceability/metals/v1",
  ],
```

or 

```
"@context": [
     "https://www.w3.org/2018/credentials/v1",
     "https://w3id.org/traceability/v1",
     "https://w3id.org/traceability/datasets/v1",
  ],
```

But for now it's better that we work together and focus on shared vocabulary as much as possible.

**Comment by TallTed** [comment]
> The work item was created specifically to address supply chain... and its not the first vocabulary to do so:

So the "traceability vocab" effort is to build and improve on existing works (including other vocabs), in various ways including by adding some supplementary/complementary vocab(s)?  Great! Please do everyone encountering the project a favor, and at least summarize the known previous works upon which foundation this effort will stand!  (This will have a secondary benefit of reducing the questions, misunderstandings, and counterproductive issues that you have to deal with from people who don't have the same starting point as you.)

Also, please don't assign issues, etc., to people without conferring with them, working to reach a common understanding among the {task force, community group, working group, etc.} of what is needed to resolve the issue, and confirming that the person(s) being assigned have the knowledge, time, and other resources necessary to satisfy that need.  I don't believe any of these elements have currently been satisfied, so I'm removing my assignment to this issue.

**Comment by OR13** [comment]
@TallTed its standard policy to assign issues to people who open them, and ask them to move the issue towards a constructive contribution. If you prefer I can close the issue now, or I can leave it open until you open a PR with changes you think would address the concern for which you raised the issue.

**Comment by OR13** [comment]
@TallTed 

> Please do everyone encountering the project a favor, and at least summarize the known previous works upon which foundation this effort will stand! (This will have a secondary benefit of reducing the questions, misunderstandings, and counterproductive issues that you have to deal with from people who don't have the same starting point as you.)

Can I retitle this issue as a request to expand the introduction and add a related work section?

**Comment by OR13** [comment]
Removing `wontfix` since the issue thread seems to be headed towards constructive additions to introduction and related work.

**Comment by TallTed** [comment]
@OR13 
> @TallTed its standard policy to assign issues to people who open them, and ask them to move the issue towards a constructive contribution. If you prefer I can close the issue now, or I can leave it open until you or someone else on this thread opens a PR with changes you think would address the concern for which you raised the issue.

"standard policy" where, for whom? You're projecting *something* onto practice within the W3 community, where there is no such "standard policy."

Issues should not be CLOSED without being ADDRESSED by more than a cursory dismissal by a single individual, regardless of that individual's role, unless that individual is the Director of W3C -- and even then, such cursory dismissal would be inappropriate, and would have a path of appeal.

WONTFIX should *NEVER* be applied to an issue raised within a W3 context after being open for all of, oh, let's see, *two hours!*  I am quite concerned with the trends here.

@kimdhamilton @wyc @vsnt -- As this is a (still only "proposed", I think?) work-item of the CCG, and you are the (current) chairs thereof, I'm afraid it's necessary to call you in.

**Comment by OR13** [comment]
@TallTed The current work item you are commenting on is not a proposal, its been under active development for some time.

This is the link to the proposal: https://github.com/w3c-ccg/community/issues/191

**Comment by mprorock** [comment]
> This is the link to the proposal: [w3c-ccg/community#191](https://github.com/w3c-ccg/community/issues/191)

Just a correction - the proposal for this current work item, "Traceability Vocabulary" is here [w3c-ccg/community#156](https://github.com/w3c-ccg/community/issues/156)

**Comment by OR13** [comment]
I think we have addressed this by updating the readme's and having regular calls. @TallTed  can you propose next steps for this issue.

**Comment by TallTed** [comment]
The "About" section of the repo homepage should be coordinated with the other content changes.  I don't know who can change this (perhaps CODEOWNERS?).  It now says --

> A vocabulary for asserting Verifiable Credentials related to supply-chain traceability

I suggest this should become --

> A traceability vocabulary for describing relevant Verifiable Credentials and their contents.


The README also needs some additional work, for which I'll submit a PR in the near future.

I think it needs something about enabling provenance-tracing of process inputs and outputs, from the most basic extraction or retrieval (e.g., ores extracted from mines in conformance with safety, wage, and other rules, regulations, policies, etc.) to the most polished output (e.g., a smartphone available for retail purchase).

**Comment by OR13** [comment]
Related to https://github.com/w3c-ccg/traceability-vocab/issues/160 can be tackled with readme updates, will also be helpful to tweak the github description and links

**Comment by mprorock** [comment]
closely related to #160

**Comment by mprorock** [comment]
welcome PRs from anyone in community on this topic, especially for overall cleanup

**Comment by OR13** [comment]
We're seeking community feedback.

**Comment by BenjaminMoe** [comment]
Needs PR against readme and repo descriptions to state that traceability is more than supply chain. Talked on call.

**Comment by TallTed** [comment]
Overtaken by events.
