### ISSUE TITLE
Tutorial needed for generator process

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/traceability-vocab#154]
Detailed on today's CCg101 call (link forthcoming)

Here's Mike's slide:
![image](https://user-images.githubusercontent.com/37127325/116317546-4fab5d00-a768-11eb-97af-c9d8778656d3.png)

**Comment by bumblefudge** [comment]
@mprorock @OR13 is this an accurate translation of the above? If so, we can get a skeletal placeholder for a tutorial up lickety split!

1. Create [syntactic] Schemata (in JSON Schema)
2. LD-ify those [syntactic] schema into [semantic] Schemata
3. Generate a JSON-LD Context (graph of expanded schemata)
4. Create test vectors (i.e. "dummy data")
5. Generate objects from vectors
6. Test those objects (syntactically)
7. Issue and Validate full example VCs (from test vector objects)
8. Generate vocabulary (kind of like an ontology)
9. Generate OpenAPI documentation

**Comment by OR13** [comment]
@bumblefudge yes please!

**Comment by bumblefudge** [comment]
there was also a question of "why generate LD from JSON Schema instead of just writing LD?" which might justify a second tutorial: how to skip steps 1-7 if you've already got valid LD Schemata and a Context file ?

**Comment by mprorock** [comment]
> there was also a question of "why generate LD from JSON Schema instead of just writing LD?" which might justify a second tutorial: how to skip steps 1-7 if you've already got valid LD Schemata and a Context file ?

while possible i personally am a fan of the rigor applied by defining a schema, as well as the additional test and verification checks that come from the current approach.

**Comment by OR13** [comment]
yep, it has been discussed in great detail in the DID WG... JSON-LD is not a schema language... and so if you want to be a bit more security minded, its good to pair it with one, like JSON Schema or CDDL.

**Comment by bumblefudge** [comment]
I think the "second tutorial" could be a deprecated aside :) 

here's the whole (sidenote **completely amazing**) pitch deck from today's session, for the archive:
[CCG 101 - VCs in a Traceability Context.pdf](https://github.com/w3c-ccg/traceability-vocab/files/6388547/CCG.101.-.VCs.in.a.Traceability.Context.pdf)

Permission to just link to this from the root readme.md?

**Comment by mprorock** [comment]
No issue at all linking to that presentation

**Comment by Therecanbeonlyone1969** [comment]
Will see if i can find someone from spherity to work on this.

**Comment by bumblefudge** [comment]
On today's call, interest was expressed in a tutorial guidance on how NOT to use generators and manually construct LD.

Notes:
- faker data creates gitflow /merge conflicts - 

completely non-generator approach:
not currently supported, tests assume generator usage. PRs welcome for test optionality.

hybrid approach:
- currently, you can BYO more or less (or no) pre-constructed schemata and still pass the tests.
- server-side node allows you to bring in your own self-generated LD code (optional step 0)

**Comment by OR13** [comment]
@bumblefudge thanks for these notes!

**Comment by bumblefudge** [comment]
downpayment on a tutorial that will be BEAUTIFUL when it's eventually PRed in :D.  in the meantime, gives people jumping in midway a notes-trail to research.

**Comment by OR13** [comment]
let's get these notes / diagrams in the readme.... what is remaining?

**Comment by nissimsan** [comment]
This will be simpler if we move to static json examples - less to document. 

Ref: https://github.com/w3c-ccg/traceability-vocab/issues/177

**Comment by OR13** [comment]
@bumblefudge do you want to keep this issue? how can we proceed?
