### ISSUE TITLE
Interop question: is there a way to access or verify Legal Entity Identities in an Indy-based OrgBook like VON?

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/traceability-vocab#155]
There was a question on today's CCG101 about how to leverage large-scale indy-based legal entity identity systems of the sort being architected by BCGov and Bosch in various jurisdictions.

I don't actually know much about this so hopefully someone who knows Indy sees this thread and knows how to advance this further! @troyronda anyone come to mind familiar with the Bosch and/or BCGov VON specifications?

**Comment by bumblefudge** [comment]
See also https://github.com/w3c-ccg/universal-wallet-interop-spec/issues/84#issuecomment-823563525

**Comment by domwoe** [comment]
Is there a recording of the call?  I'd like to get more context on this.

**Comment by kdenhartog** [comment]
Happy to help on this if I can or at least connect the right people @swcurran would be the first one I'd think could help provide more clarity.

From my perspective, VON is effectively just a web service that hosts verifiable credentials that are publicly available (and usually searchable via a browser). Assuming the issuer of the credentials hosted in the registry is trusted then a chain of trust could be used to link from a known trust anchor who issues the credentials that go into the registry. The issuer is also likely to be the host of the registry, but doesn't have to be. Then the registry credential asserts a known link between an org and their legal entity identifier which could be a DID, but may just be a public key at a .well-known enpoint. This LEI would then be used to issue traceability credentials and pass them along with products, publicly provide them (probably not likely - supply chain info is sensitive and proprietary often) or via some other means.

That's my take of how this might be connected to the LEI work happening with Indy networks and VON.

**Comment by swcurran** [comment]
VON, or more precisely Aries Verifiable Credential Registry (Aries VCR) is a bootstrapping mechanism for the use of credentials, enabling an authority to issue public credentials to a service that can be checked by anyone -- for example a registrar of organizations to issue public credentials about registered organizations. As @kdenhartog -- there is only an incremental amount of trust added by the service (it does add verifiable credentials vs. unsigned data).

We're excited about the work we're doing with Bosch on the Business Partner Agent (BPA). A quick summary of one part of the vision for that.  Every organization runs a BPA -- an organizational wallet.  Registrars of organization issue to the BPA for a registered entity issue a verifiable credential to their wallet.  They can use that to prove who they are from an authority. 

Extend that out to also being issued a credential that they have some other authority -- perhaps they are a University and they have authorization to issue diplomas. They issue verifiable credentials to students.  When the students present those VCs, the verifier verifies the and if valid, can contact the BPA of the issuer to ask who they are (registration) and under what authority they issued the credential. The BPA can present the VCs they hold and if the original verifier recognizes them -- all good.  If not, they recursively request the same info from the issuers of those VCs and so.  If no recognized issuers are ever found -- back to the same thing we do today -- pass the information to a human to do some research and make a "trust yes/no" decision about each participant in the chain -- and cache that for the next verification.

Both Aries VCR (and it's related issuers) and the BPA are built on top of an Aries stack. This allows use with Indy AnonCreds VC formats today. Of course, as with everything related to Aries, we're adding support for other VC formats (JSON-LD, BBS+) and ledgers.

**Comment by OR13** [comment]
seems like the question is answered a bit, do we need an example in the spec? Do we need an informative section? How might be update the "Organization" type?

**Comment by Therecanbeonlyone1969** [comment]
I do not think that the spec needs to talk about legal identity interoperability because it is a jurisdictional question or enterprise trust-relationship question and will be context-dependent. We would have to create a list of registries and their interfaces if this were to be of value to implementers, similar to the DID method registry.

**Comment by OR13** [comment]
on the call today, we discussed needing a section of the spec that comments on the relationship between credentials and public registries.

**Comment by mprorock** [comment]
@OR13 can this be closed? or do we need to add a spec section still? you added the read-for-pr tag on 7/12/21

**Comment by mprorock** [comment]
per discussion on call - this may be out of scope

**Comment by nissimsan** [comment]
+1 on the call discussion: endorsing DID registries is not in our scope. Also, it seems to conflate did vs. vc as the solution to addressing legal entities.

We might consider including/endorsing the LEI and other similar "trusted party"/"economic operator" credential schemas.

**Comment by OR13** [comment]
We think this is out of scope, perhaps the only part relevant to us would be informative guidance on governance, which is better addressed in a separate issue.
