### ISSUE TITLE
Suggest a couple of additional features

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [w3c-ccg/traceability-vocab#158]
A couple of questions that would lead to some extended functionality, if implemented:

1. should we add a configuration file for credential test fixtures? This would allow for example to add `evidence` and/or `credentialStatus` variably to a VC, if so desired.
2. Should we add BBS+ signatures besides Ed25519 by adding another key into the DID doc we are currently using? This would double the number of test fixtures for credentials unless we add two proof entries (one for Ed25519 and one for BBS+) when we issue a VC.
3. Should we add a base schema for `evidence` and `credentialStatus` to the context file? If people want more they could add it as a separate schema. However, to get started a simple one that everyone uses might be worthwhile.  

I would be happy to add that functionality as I have done that already in another vocab and it works nicely after some trial and error.

Thoughts? cc @bumblefudge @mprorock @OR13

**Comment by OR13** [comment]
Lets try and focus this issue on JSON Schema for `Evidence`  / `credentialStatus`. and punt signature suite stuff to interop profile.

**Comment by OR13** [comment]
@mprorock noted on the call that Ag use cases also needs support for evidence.

**Comment by OR13** [comment]
@Therecanbeonlyone1969 we need to sync on this on a call / slack and make a proposal for moving things forward.

**Comment by Therecanbeonlyone1969** [comment]
@OR13 @mprorock the call dropped off my calendar smh ... could someone resend the invite?

**Comment by Therecanbeonlyone1969** [comment]
> Lets try and focus this issue on JSON Schema for `Evidence` / `credentialStatus`. and punt signature suite stuff to interop profile.

@OR13 ... sure. Whatever works. Just threw out some ideas.

**Comment by bumblefudge** [comment]
@OR13 maybe worth linking to this issue in an email to the list as a "roadmapping"/stack-ranking item on the agenda for next week? that way anyone with Strong Opinions™ on these features will be motivated to come, bring opinions, volunteer for a PR, etc? Just an idea, need not be next week

**Comment by OR13** [comment]
Discussed on the call, this should be addressed when the linked PR is split up.

**Comment by TallTed** [comment]
Retitle and/or re-description would be helpful, if this has indeed narrowed.  Else, I'd suggest splitting to (at least) one issue per "additional feature"

**Comment by OR13** [comment]
We think this was handled in previous PRs
