### ISSUE TITLE
Edit README etc to more accurately reflect current roles and process

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/traceability-vocab#160]
From README --
```
Any changes that potentially introduce breaking or non-backwards compatible
functionality MUST have a corresponding issue and discussion, and will require
consensus from the editors in order to be introduced or to have any related Pull
Requests accepted and merged.
```

It is highly unusual for the Editors to have this much preemptive power over anything in a W3 group of any kind, even "changes that potentially introduce breaking or non-backwards compatible functionality".

I think this policy needs some reconsideration, and the README will then need some new wording.

**Comment by wyc** [comment]
As per the [Consensus](https://www.w3.org/2020/Process-20200915/#def-Consensus) defn:
> A substantial number of individuals in the set support the decision and nobody in the set registers a Formal Objection. Individuals in the set may abstain. Abstention is either an explicit expression of no opinion or silence by an individual in the set.

@TallTed do you feel that changing "editors" to "work item contributors" would help address this concern?

**Comment by TallTed** [comment]
@wyc -- Yes, that would help some. Broader point is that output of Work Items and/or Task Forces is aiming toward being output of CCG, and the content (and decisions about that content) should be being made by the group members, not by Editors nor Chairs nor WI/TF facilitators.

**Comment by kdenhartog** [comment]
I'm +1 to this. This should allow the subset of work item contributors to keep work on work items moving forward while also allowing for the broader CCG audience to be able to engage on topics of interest to express support or dissent when they feel necessary.

**Comment by OR13** [comment]
@TallTed to re-title issue, work through proposal for README updates / contributing guide updates.

**Comment by OR13** [comment]
@TallTed we discussed this on the call, readme still needs to be updated.

**Comment by OR13** [comment]
we discussed on the call, still needs to be updated.

**Comment by mprorock** [comment]
discussed on call and will update when we add first non supply chain vocab elements

**Comment by TallTed** [comment]
offending text is now in https://github.com/w3c-ccg/traceability-vocab/blob/main/DEVELOPMENT.md#making-contributions

**Comment by OR13** [comment]
@nissimsan please address this issue in the same PR you use to address #307.

**Comment by brownoxford** [comment]
Discussed on call and consensus was to pending-close this issue.

**Comment by TallTed** [comment]
Overtaken by events
