### ISSUE TITLE
Add examples of paper forms for digital credential formats

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#161]
Lets gather examples on the issue, and then work towards a proposed PR to add examples.

**Comment by mprorock** [comment]
also including how we go from paper to json schema to linked data

**Comment by Therecanbeonlyone1969** [comment]
@OR13 @mprorock as a way of example, the eCommerce waybill schema in the repo is a one-to-one translation of the IATA Airwaybill form.

**Comment by OR13** [comment]
We need images or:

- CMTR
- Commercial Invoice
- Bill of Lading
- Ag Inpspect

etc..

**Comment by nissimsan** [comment]
I can assist with this

**Comment by OR13** [comment]
Maybe search for blank forms as well.

**Comment by mkhraisha** [comment]
our Observations list come from here for example: https://corporate.exxonmobil.com/Crude-oils/Crude-trading/Assays-available-for-download

**Comment by OR13** [comment]
Examples for BOLs.... https://github.com/transmute-industries/iata-one-record-hackathon-2021/tree/main/public/sanitized-bols

**Comment by OR13** [comment]
we did it fam

**Comment by mprorock** [comment]
Per call - already covered in multiple examples
