### ISSUE TITLE
Need ability for inheritance on json schema

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-vocab#162]
In an ideally world we could use `allof` or similar in JSON Schema to represent a class - subclass relationship - this type of thing is well handled in JSON-LD, less so in JSON Schema.  We should pick a best practice on this, and document it, etc.

**Comment by mprorock** [comment]
for example, in terms of the ag use case, we cannot type check that ppq203 is a subclass of aginspection in the repo

**Comment by Therecanbeonlyone1969** [comment]
Recommend to strive for a composable structure that is like:

1. General structure of properties we deem as common and decide if those are to be required
2. Extension schemas through `$ref` for verticals with these schemas to be composable and thus extensible again to other sub-schemas

example of an approach is: 

- https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/schemas/EcommerceWayBillRegistrationEvidenceDocument.json
- https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/schemas/EcommerceWayBillCommodityContent.json
- https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/schemas/EcommerceWayBillTotals.json
- https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/schemas/PriceSpecification.json

**Comment by mprorock** [comment]
note: hardening any type enforcement should likely come into play once it is known that the object fully represents the contents of the type - e.g. paper based form that does not change or changes only on a long time scale, and is being digitized (e.g. digital form of a regulatory document)

**Comment by OR13** [comment]
JSON Schema that use inheritance do not generate JSON-LD context properly.

**Comment by OR13** [comment]
We still need examples.

**Comment by mprorock** [comment]
Per Call: This is resolved via #220

**Comment by VladimirAlexiev** [comment]
@OR13 
> JSON Schema that use inheritance do not generate JSON-LD context properly.

JSON Schema does not generate JSON-LD context of its own. So can you please illustrate the problem?

@mprorock 
> resolved via https://github.com/w3c-ccg/traceability-vocab/pull/220

Can you please explain how this is resolved by pointing to schemas that use inheritance?

I'm asking in relation to 2 of the issues I posted:
- #277 asks to use inheritance rather than composition, and  gives an example of need for inheritance ("SeafoodProduct inherits from AgProduct and MarineProduct"), 
- #571 gives another example ("NaturalGasProduct inherits from Product and adds HSCode; and changes facility to OilAndGasFacility").

**Comment by OR13** [comment]
> JSON Schema does not generate JSON-LD context of its own. So can you please illustrate the problem?

We do this in this repo, its part of our build step today:

https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/package.json#L17
