### ISSUE TITLE
Get default agenda into CCG calendar

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/traceability-vocab#166]
1. IP Note, Agenda Review, Scribe Selection (5 minutes)
2. GitHub Issue & PR review (Core vocab)
3. GitHub Issue & PR review (Core vocab documentation)
4. GitHub Issue & PR review (VC-HTTP-API extensions repo)
5. GitHub Issue & PR review (Interop repo)
6. Proposals to Address Challenges
7. Next Steps

**Comment by bumblefudge** [comment]
(not editor, can't assign to @mprorock but he said on the call he would assign it to himself)

**Comment by OR13** [comment]
@mprorock please confirm this is all done, and then let us know if we can close.

**Comment by OR13** [comment]
discussed on the call today, closing as done.
