### ISSUE TITLE
SubEvents need to be defined 

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#167]
We need sample definitions for events as defined in #164 

PR #164 adds a simple root event without any event subtypes. We need EPCIS events that define 

- observation
- transformation
- aggregation
- disaggregation
- commission
- decommission

The initial action is to provide one of these events and then after discussions create the rest.

**Comment by OR13** [comment]
@mkhraisha to add a description / action.

**Comment by mkhraisha** [comment]
@mprorock any idea if there are any EPCIS events for Storage and Transportation?

**Comment by OR13** [comment]
https://github.com/gs1/EPCIS/blob/5f1998aff6540e2ac11727ff085eb7ac1eaa1b3c/Ontology/CBV.ttl#L428

**Comment by mprorock** [comment]
discussed on call - have root event that has generic event, need EPCIS events added as sub-classes - @mkhraisha will PR

**Comment by OR13** [comment]
@mkhraisha any update on this?

**Comment by BenjaminMoe** [comment]
Pending close due to inaction.

**Comment by brownoxford** [comment]
Discussed on call, closing. This is done.
