### ISSUE TITLE
Need for Ag Inspection Report Schema

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/traceability-vocab#18]
I've created a schema for an Inspection Report that is specific for agriculture inspection, using the InspectionReport schema as a foundation.  I'll submit a PR for review (@mprorock and @OR13 ) once I get permission to create a branch or I'll just fork it.

**Comment by OR13** [comment]
Assigning you both to add the schema / tests needed for this.

**Comment by mprorock** [comment]
In progress, thansk!
