### ISSUE TITLE
Ask JSON-LD and JSON Schema WGs/teams for help with making JSON-LD Schema

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#185]
See comments on https://github.com/w3c-ccg/traceability-vocab/issues/150

We resolved this resolution on todays call, this issue is opened to track ensuring that feedback is requested from both groups.

- [ ] CG has requested feedback from JSON-LD WG
- [ ] CG has requested feedback from JSON Schema WG

**Comment by mprorock** [comment]
@OR13 any updates?

**Comment by OR13** [comment]
Some conversations with the semantic wg:

https://lists.w3.org/Archives/Public/semantic-web/2022Feb/0027.html

**Comment by OR13** [comment]
We may also want to reach out to OAS3.0 folks to gather there feedback... and possibly the LinkML.

**Comment by BenjaminMoe** [comment]
Nothing concrete to comment on currently. We have some contact with JSON-LD.

**Comment by OR13** [comment]
I suggest we close this.

**Comment by brownoxford** [comment]
Closing
