### ISSUE TITLE
PROPOSAL: We will use OAS3.0 YAML Schemas in trace vocab, instead of JSON Schema in JSON

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#186]
This proposal has not been resolved.

We have deferred this proposal to next meeting, and the issue is opened to gather feedback on exactly what such a change would look like.

As you can see, OAS 3.0 provides examples in JSON and YAML:

- https://swagger.io/specification/

Here is an example of a [Verifiable Credential Schema in OAS3.0 represented as YAML](https://github.com/w3c-ccg/vc-http-api/blob/main/components/VerifiableCredential.yml) 

Here is an example of a [Verifiable Credential Schema in JSON Scheam with $comment](https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/schemas/CommercialInvoiceCertificate.json)

This proposal would be to convert all files in https://github.com/w3c-ccg/traceability-vocab/tree/main/packages/traceability-schemas/schemas to YAML which supports comments, and to ensure that they are 100% going to be compatible with vc-http-api.

**Comment by mkhraisha** [comment]
I was under the impression that OAS3.0 was mainly intended as a way to document web-apis, this however looks much cleaner than what we currently have. huge +1

**Comment by TallTed** [comment]
If I understand this correctly, it seems that —

> PROPOSAL: We will use OAS3.0 YAML Schemas in trace vocab, instead of JSON Schema in JSON.

— would be clearer and more internally consistent if rewritten as —

> PROPOSAL: The trace vocab will use OAS3.0 Schemas represented in YAML, instead of JSON Schema represented in JSON.

?

**Comment by mprorock** [comment]
related to #189 - @mkhraisha would like this prior to a v1

**Comment by mprorock** [comment]
dupe #189
