### ISSUE TITLE
Update JSON Schema to YAML and OAS3.0

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#189]
RESOLVED: The trace vocab will use OAS3.0 Schemas represented in YAML, instead of JSON Schema represented in JSON.

**Comment by TallTed** [comment]
per #186

**Comment by tobek** [comment]
I'm sure I'm missing some context here, but does this proposal supercede #184 and #185, or will JSON Schemas still be maintained (and JSON-LD contexts still generated from them)?

For our (@SertoID) work we plan to keep using JSON Schema for validation and VC [`credentialSchema`](https://www.w3.org/TR/vc-data-model/#data-schemas) field purposes, and I'm curious what other projects are planning here.

**Comment by OR13** [comment]
@tobek I think for this repo, we would switch to yaml, but the underlying library would continue to support YAML or JSON schema.... I suspect we can even make the `$comment` vs `$linkedData` a backward compatible feature of the tool.

similar to how OAS3.0 works today, I think constraining data shape with YAML or JSON schemas will be part of the next vc data model, and hopefully better documented in the next version.

**Comment by OR13** [comment]
but to be clear, we are hoping to switch to yaml representation of JSON schema here, to make interactions with OAS3.0 easier.

**Comment by OR13** [comment]
Upstream implementation updated to support this: https://github.com/transmute-industries/verifiable-data/pull/118

**Comment by OR13** [comment]
This is done, I am closing.
