### ISSUE TITLE
PROPOSAL: Define inheritance model for *Certificate "VerifiableCredential types"

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#191]
https://w3c.github.io/vc-data-model/#types

This would be a JSON Schema which defined common terms for "Verifiable Credential types"...

Note that a verifiable credential type is different than a "credentialSubject type or credentialSubject claim type"

**Comment by mprorock** [comment]
big fan of this - multiple types are very key for semantic understanding of the data on our side, as well as for validation

**Comment by mprorock** [comment]
at a minimum we could include:

- name
- description
- use of object for issuer
- use of object for subject

**Comment by mkhraisha** [comment]
* Require place under issuer object

**Comment by mkhraisha** [comment]
* Require Credential status

**Comment by OR13** [comment]
I would be open to "defining place and credential status"... but not to requiring them.

**Comment by OR13** [comment]
Related to credentialStatus https://github.com/w3c-ccg/traceability-vocab/issues/47

**Comment by mkhraisha** [comment]
Certificate forms should have a link to external forms and examples

**Comment by mprorock** [comment]
Per call: resolved in #220
