### ISSUE TITLE
PROPOSAL: Define a tagging structure for grouping schema objects

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#192]
- [x] Move industry specific credentials to a folder
- [x] Add OAS tags to each credential

**Comment by mprorock** [comment]
lower priority, but we would like the ability to tag credentials by use case, common usage, etc - closely related to #193 and both could be potentially resolved with a common approach

**Comment by mprorock** [comment]
#220 appears to handle some of this nicely

**Comment by OR13** [comment]
There is a proposal embedded in https://github.com/w3c-ccg/traceability-vocab/pull/220

**Comment by nissimsan** [comment]
I love this!

**Comment by OR13** [comment]
We support this now, via Tags, however we should probably leave this open until we fix the folder structure issues, and are using tags properly.

**Comment by BenjaminMoe** [comment]
We've started with folders. Need to make use of tags in OAS.

**Comment by BenjaminMoe** [comment]
Move to new issues and close.

**Comment by BenjaminMoe** [comment]
I dont think we gain too much advantage from separating credentials by industry folder. I think our folder structure should be `common`, `credentials`, `presentations`. And then we can use OAS tags to sort and search within those folders.

**Comment by OR13** [comment]
I suggest closing, as done.
