### ISSUE TITLE
PROPOSAL: Implement a folder structure that separates and groups schemas

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#193]

**Comment by mkhraisha** [comment]
This should probably include a standardization of how we name files.

**Comment by mprorock** [comment]
support for both inheritance and encapsulation should be accounted for by an optimal folder structure

**Comment by mkhraisha** [comment]
Possible Paths:
```
Common:  Bill of Lading
Certificates: Verticals : OG OGBOL
                        : Steel SteelBillOfLading
                        : AG AGBOL

**Comment by OR13** [comment]
I've seen 2 main folder structures for large projects:

### Feature Oriented

```
/common
/shipping/bill-of-lading
/shipping/bill-of-lading/consignee
etc... (nested hierarchies grouped by feature level value)
```

### Layer Oriented

```
/common
/bill-of-lading
/consignee
etc... (flat collections grouped by architecture layer)
```

See also [this](https://softwareengineering.stackexchange.com/questions/338597/folder-by-type-or-folder-by-feature/338601#:~:text=Folder%2Dby%2Dfeature%20is%20superior,file%20you%20are%20looking%20for.)

**Comment by nissimsan** [comment]
Beautiful suggestion, @mkhraisha. Does the common-to-vertical specific entail inheritance? 
Like: OGBillOfLadingCertificate allOf:  BillOfLading?

**Comment by mkhraisha** [comment]
> I've seen 2 main folder structures for large projects:
> 
> ### By Feature
> ```
> /common
> /shipping/bill-of-lading
> /shipping/bill-of-lading/consignee
> etc... (nested hierarchies grouped by feature level value)
> ```
> 
> ### By Type
> ```
> /common
> /bill-of-lading
> /consignee
> etc... (flat collections grouped by architecture layer)
> ```
> 
> See also [this](https://softwareengineering.stackexchange.com/questions/338597/folder-by-type-or-folder-by-feature/338601#:~:text=Folder%2Dby%2Dfeature%20is%20superior,file%20you%20are%20looking%20for.)
> 
> I tend to prefer by feature.

I usually prefer by feature, however I believe most of the people using the repo will care more about things within a certain vertical rather than for a specific feature across verticals, and I believe a Type separated by vertical is probably best

**Comment by mkhraisha** [comment]
> Beautiful suggestion, @mkhraisha. Does the common-to-vertical specific entail inheritance?
> Like: OGBillOfLadingCertificate allOf: BillOfLading?

I believe every item in Certificate needs to inherit or encapsulate an item from common in my suggestion.

**Comment by mkhraisha** [comment]
Suggestion 2: The names of the files should reflect their nature i.e. Certificates should be suffixed with Certificate whereas common files should not have a suffix.

**Comment by mkhraisha** [comment]
Suggestion 3: The names of the files should be prefixed with their vertical. this should only apply to things in their respective vertical certificates folder and not to items in the certificates/common folder. This should not apply to any items in the common root folder.

**Comment by nissimsan** [comment]
> > I believe every item in Certificate needs to inherit or encapsulate an item from common in my suggestion.
> 
> yes, eg `AgInspection` has `allOf:Inspection`

Again: I find this beautiful. I do worry, though, if it is taking a step too far. We wanted to "support" inheritance; this sort of "requires" inheritance.  

It'll be fine as long as we're building from scratch. But say we wanted to support both IATA's Air Waybill and DCSA's Sea Waybill; these are schemas which have been developed individually, and I worry that it will be difficult to define a common super-schema?

**Comment by TallTed** [comment]
@nissimsan — Don't let perfect get in the way of useful. The schemas a/k/a ontologies for IATA's Air Waybill and DCSA's Sea Waybill seem likely to be very similar. `skos:narrower`, `skos:broader`, `owl:similarProperty`, `owl:similarClass`, `owl:equivalentProperty`, `owl:equivalentClass` (and in rare cases, `owl:sameAs`) are good for drawing the connections between these schemas/ontologies. There's no need to build One Schema To Rule Them All — just include some sort of reasoning engine in the mix! But of course, when you find, for instance, that Virtually Every Shipping Document Ever includes a block for a human contact's details, it will make sense to describe all the various specific-document entities and attributes as sub-classes and sub-properties of the GenericShippingOntology you eventually concoct *based on experience, rather than conjecture.*

**Comment by mkhraisha** [comment]
Suggestion that includes all of them

```
/common
/common/shipping/bill-of-lading.json
/agriculture/shipping/AGBillOfLadingCertificate.json
/oil/shipping/OilBillOfLadingCertificate.json
```

**Comment by OR13** [comment]
closing see the link above.
