### ISSUE TITLE
Need the ability to capture standalone data around possible cross border movement early in the supply chain process

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-vocab#194]
regarding pr #187 and [Intent to Sell](https://w3c-ccg.github.io/traceability-vocab/#IntentToSell) overlap - we need a manner to capture early in the process of potential cross border movements stand alone details regarding possible movements of a product.

at a minimum we need to capture: 

* who is initiating or planning the movement of an item across a border
* who that party is planning on sourcing the goods from
* what is product or item is planned for import
* that when that movement may occur

and possibly:
* what is the status of this, planning, actually in the process of importing it, changed your mind, etc

**Comment by mprorock** [comment]
note: a path we would be happy with would be renaming "Intent to Sell" to "Intent to Import" and that would satisfy our needs

We have a need for this information outside of customs and regulatory processes, especially for looking at potential cross border contamination or invasive species tracking, etc

**Comment by OR13** [comment]
Lets gather requirements here first, before continuing to discuss ITI.

**Comment by Therecanbeonlyone1969** [comment]
Requirements (E-Commerce Sector):

- Heterogeneous “data shards” from various supply chain actors must be combinable into a meaningful and coherent mosaic for each E-Commerce transaction and shipment
- Timely notification of events, documents, and expected volumes at every point of the supply chain
- Timely identification and notification of “anomalies”
- Adaptive and linked data feeds to provide predictive analytics, real-time intelligence, and ongoing supply chain traffic analysis to combat abuses such as counterfeiting, illicit goods, duty evasion and improve delivery times
- Speed-up customs processes and enable faster delivery to consumers

**Comment by nissimsan** [comment]
Supply Chain Requirements: 
- Indication of the reason why the presenter is submitting the presentation
- Acknowledgement and acceptance of liability involved in making the presentation
- References between presentations, allowing updates and corrections

Proposed Solution: 
The above requirements can be solved with two attributes: `correlationId` and a short, free form `message`. 

Suggested Options: 
1. We rename "Intent to Sell" to "Intent to Import", adding the above two attributes. We keep all attributes optional, so each they can be used where applicable. 
2. We keep "Intent to Sell" and add a separate "Intent to Import" with just the two above attributes.

**Comment by mprorock** [comment]
@nissimsan definitely prefer option 1 - rename

**Comment by mkhraisha** [comment]
I think we need to have a conversation about `correlationId` for a bunch of other use cases too, it should be set as its own issue.

For ITI , I think there is an issue where ITI is not a real-world process and is not currently used by any customs, and i'm not sure if its supposed to have its own thing.

There was a point of contention between what @mprorock and what @nissimsan is trying to do.

**Comment by TallTed** [comment]
We should fully implement the existing ITS process and forms, and then embellish (add checkboxes and/or other fields) to make the additional ITI process that DHS is reportedly pressing for.

**Comment by nissimsan** [comment]
I support the direction we were heading on yesterday's call: let ITI support existing, paper-based processes when presented at time of import; but also allow for the ambition of more timely/earlier import submissions.

**Comment by mprorock** [comment]
> We should fully implement the existing ITS process and forms, and then embellish (add checkboxes and/or other fields) to make the additional ITI process that DHS is reportedly pressing for.

Per discussion on call: this documentation step should be path forward

**Comment by nissimsan** [comment]
OK, so we're good with the ITS as is. Adding a separate ITI should be a separate issue, to be raised when clearer requirements emerge. Closing.
