### ISSUE TITLE
Standardizing Way Bills on the IATA Airfreight Way Bill standard

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [w3c-ccg/traceability-vocab#195]
**Proposal**
Use the IATA Airfreight Way Bill standard -- https://www.iata.org/en/programs/cargo/e/eawb/ -- for all Way Bills.

Implementation of IATA Way Bill are here:

- https://w3c-ccg.github.io/traceability-vocab/#EcommerceWayBillRegistrationCredential
- https://w3c-ccg.github.io/traceability-vocab/#EcommerceWayBillRegistrationEvidenceDocument

and associated sub-schemas

**Comment by mprorock** [comment]
Per Call: addressed with pr #249
