### ISSUE TITLE
Continuous Integration & Synthetic Data

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#20]
We would to have confidence that the schemas and contexts and spec are all "passing" on every PR.

We would also like to have code that generates synthetic data that allows those tests to pass.

This issue is to discuss how to structure this using javascript in this repo.

**Comment by OR13** [comment]
Partially implemented, but the order to of the tests does not enforce this the way I would like.

We should generate the spec THEN run the CI tests.

if either fails the PR fails.

**Comment by brianwmunz** [comment]
@OR13  Do the changes I made to the readme and adding the build process in #43 address this issue?

**Comment by OR13** [comment]
We need to add `build` here https://github.com/w3c-ccg/traceability-vocab/blob/main/.github/workflows/ci.yml

then we can close this.
