### ISSUE TITLE
Upgrade Node Version

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#202]
We're currently using Node 12 ( at least according to CI) which is currently in maintenance LTS.
We should migrate to at least Node 14, I advocate we go to 16 though.

![image](https://user-images.githubusercontent.com/19310771/134203308-e8e6662e-fa54-4d94-a4dd-9afec9bd07e9.png)

**Comment by OR13** [comment]
We should use node 14.

**Comment by mprorock** [comment]
node 14
