### ISSUE TITLE
Measured vs Quantitative Value

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#204]
What is the difference between Measured and Quantitative Values?

Measured Value: https://github.com/w3c-ccg/traceability-vocab/blob/73eeb16cea9dec42239190d48e1cc80b803021a6/packages/traceability-schemas/schemas/MeasuredValue.json#L6

Quantitative Value: https://github.com/w3c-ccg/traceability-vocab/blob/73eeb16cea9dec42239190d48e1cc80b803021a6/packages/traceability-schemas/schemas/QuantitativeValue.json#L6

Both appear to be using the same Schema.org definition.

**Comment by TallTed** [comment]
@mkhraisha -- Links to existing definition(s) would be helpful...

**Comment by mkhraisha** [comment]
Measured Value: https://github.com/w3c-ccg/traceability-vocab/blob/73eeb16cea9dec42239190d48e1cc80b803021a6/packages/traceability-schemas/schemas/MeasuredValue.json#L6

Quantitative Value: https://github.com/w3c-ccg/traceability-vocab/blob/73eeb16cea9dec42239190d48e1cc80b803021a6/packages/traceability-schemas/schemas/QuantitativeValue.json#L6

**Comment by mkhraisha** [comment]
Updated

**Comment by TallTed** [comment]
I would say that <https://w3id.org/traceability/schemas/MeasuredValue.json> should point to <https://www.schema.org/hasMeasurement>, not <https://www.schema.org/QuantitativeValue>.

**Comment by mprorock** [comment]
> I would say that https://w3id.org/traceability/schemas/MeasuredValue.json should point to https://www.schema.org/hasMeasurement, not https://www.schema.org/QuantitativeValue.

Generally agree - i would note that hasMeasurement is still marked pending incorporation by my read and I think that was likely a motivation to use quant value - also verbiage as a getter is odd to me in this context.

**Comment by OR13** [comment]
http://www.qudt.org/ also.

**Comment by mprorock** [comment]
we also have a need for categroical classes in a mix with quant values - e.g. "too low to measure" vs "5" of some thing

**Comment by nissimsan** [comment]
I'll give this a go

**Comment by OR13** [comment]
Suggest we ask the lists regarding this.

**Comment by nissimsan** [comment]
I suggest we change 'MeasuredValue` to https://service.unece.org/trade/uncefact/vocabulary/uncefact/#Measurement.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/34443212/196175988-0b07b655-7b73-4e97-a2cf-b3c1e77ba41f.png">

It has a relevant code list of typeCodes too: 
https://service.unece.org/trade/uncefact/vocabulary/uncl6311/

**Comment by nissimsan** [comment]
Provide example of measurements. Propose here, then we can move to a PR.

**Comment by mkhraisha** [comment]
Nis on call: 

If you have a measurement use MeasuredValue, if it is a quantity use Quantitative Value.

**Comment by mkhraisha** [comment]
Closing issue as answered
