### ISSUE TITLE
Outsource getContextFromIntermediate to transmute/verifiable-data's jsonld-schema package

### ISSUE THREAD

**Issue by rhofvendahl** [w3c-ccg/traceability-vocab#205]
This addresses an issue raised in [issue 88](https://github.com/w3c-ccg/traceability-vocab/issues/88), "Issues in referencing multiple items pointing to the same IRI".

In addressing issue 88 OR13 altered `getIntermediateFromDirectory` to import a [similar function](https://github.com/transmute-industries/verifiable-data/blob/main/packages/jsonld-schema/src/schemasToContext.ts) from transmute/verifiable-data's jsonld-schema package which added properties with duplicate IRIs as arrays attached to `classProperties`.

In order for this change to work with the rest of the traceability-vocab pipeline, we'll need to do something similar to the `getContextFromIntermediate` function (in [getContextFromIntermediate.js](https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/scripts/getContextFromIntermediate.js)), as well as altering the jdson-ld-schema package to export the corresponding function (already coded by OR13).

CC: @OR13, @mprorock

**Comment by rhofvendahl** [comment]
Updating `getContextFromIntermediate` to import from transmute/verifiable-data fixed the one error I was having, but it actually looks like both `getOpenApiFromIntermediate` and `getVocabFromIntermediate` have similar issues.

I can do something similar for these, importing updated functions that check for arrays and, if found, loop through them. Before I do though, @OR13 do you think it would make sense either to make every property value an array of all properties with the same ID (even if there's only one), or else to avoid arrays entirely & use some unique key (like `` `${comment['term']}-${comment['@id']` ``)? I know neither are ideal, but consistency might be nice for other functions that use `intermediate`.

CC: @mprorock

**Comment by OR13** [comment]
We did this.
