### ISSUE TITLE
CD pipeline error

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#207]
The CD pipeline choked on my recent PR: 
https://github.com/w3c-ccg/traceability-vocab/actions/runs/1308699511

`main` renders fine locally: 
![image](https://user-images.githubusercontent.com/34443212/137301936-ee532233-29f7-4463-b696-0135e010b8f9.png)

**Comment by OR13** [comment]
cc @mkhraisha  @mprorock  i suspect this is maybe related to the versioning feature.

**Comment by OR13** [comment]
Closing, the pipeline is working.
