### ISSUE TITLE
Schema validation errors

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#209]
I'm getting the below validation errors on my recently added schemas. They don't seem to have any negative consequences, but it would still be good to understand what causes them and getting it resolved. 

Note that `DocumentVerificationEvidence` and `RevocationList2020Status` are not "mine". 

I'd appreciate any pointes as to what might cause these? 

```
traceability-schemas: Validation results:
traceability-schemas:  [
traceability-schemas:   { obj: 'CargoItem', status: 'FAILED' },
traceability-schemas:   { obj: 'DocumentVerificationEvidence', status: 'FAILED' },
traceability-schemas:   { obj: 'PartOfOrder', status: 'FAILED' },
traceability-schemas:   { obj: 'RevocationList2020Status', status: 'FAILED' },
traceability-schemas:   { obj: 'ShippingInstruction', status: 'FAILED' },
traceability-schemas:   { obj: 'ShippingStop', status: 'FAILED' },
traceability-schemas:   { obj: 'TransportDocument', status: 'FAILED' }
traceability-schemas: ]
```

**Comment by OR13** [comment]
This issue has been overtaken by events, we opened newer issues to track any active schema validation concerns after switching to OAS 3.
