### ISSUE TITLE
Don't invent new DateTime types

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#213]
originally from https://github.com/w3c-ccg/traceability-vocab/pull/210/files#r736753663

all instances of:

```
\"@type\": \"https://w3id.org/traceability#DateTime\"
```

should be like https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v1#L44:

```
\"@type\": \"http://www.w3.org/2001/XMLSchema#dateTime\"
```

**Comment by rhofvendahl** [comment]
Addressed in https://github.com/w3c-ccg/traceability-vocab/pull/228

cc: @OR13

**Comment by OR13** [comment]
cc @nissimsan

**Comment by nissimsan** [comment]
Excellent input - many thanks @VladimirAlexiev. On it...!

**Comment by OR13** [comment]
We did it.
