### ISSUE TITLE
Generate JSON Schemas from available CEFACT XSDs

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#216]
UN/CEFACT defines a number of schemas: 
https://unece.org/trade/uncefact/mainstandards
For example a very elaborate and broadly used Cross Industry Invoice: 
https://service.unece.org/trade/uncefact/publication/Supply%20Chain%20Management/CrossIndustrySCRDM/SCRDM/XSD/schema.zip

What would be the process of transforming these XSDs into JSON schemas which we can use as starting points for trace-vocab schemas? 

I don't imagine these CEFACT schemas can be imported into trace-vocab completely automated. But JSON schemas would be a good starting point for subsequent specification, especially decisions at the LD layer.

**Comment by VladimirAlexiev** [comment]
@nissimsan How does that CrossIndustrySCRDM compare to [UN/CEFACT - Buy Ship Pay Reference Data Model](https://service.unece.org/trade/uncefact/vocabulary/uncefact/)?

You already use [Consolidated Code List 1153 - Reference code qualifier (20B)](https://service.unece.org/trade/uncefact/vocabulary/uncl1153/) which I think is part of the above,
and the above has JSONLD ontology and JSONLD context, which should save a lot of trouble.

**Comment by nissimsan** [comment]
@VladimirAlexiev, both are constructed from the same UN/CEFACT core component library. The Cross Industry Invoice (CII) is a subset, exported as XSD with no formal/machine-understandable referencing back to the library. It predates the [UN/CEFACT vocab](https://service.unece.org/trade/uncefact/vocabulary/uncefact/), which is a full JSON-LD representation of the UN semantic library.

What I'm suggesting here is to find a way to reap as much benefit from the CII and other already defined and established schemas as possible. Even if we just get an "empty shell" JSON schema which we have to fill in manually with formal term definitions, that beats starting all the way from scratch. 

Yes, that code list - and many others - are part of the UN/CEFACT vocab. It makes me very happy that you call out this vocab!

**Comment by VladimirAlexiev** [comment]
@nissimsan does Traceability leverage `UN/CEFACT - Buy Ship Pay Reference Data Model` as much as possible?

Looking at https://w3c-ccg.github.io/traceability-vocab/#vocabulary-linkage and then the JSON schemas:
- I saw big chunks from DCSA EBL, IATA AirWayBill, schema.org
- Smaller chunks from gs1.org/voc
- But tiny chunks from UNCEFACT?

**Comment by nissimsan** [comment]
@VladimirAlexiev, the answer to that question is no. But there is 100% more cefact vocab usage than there were 3 months ago. This repo started from the technology side, and is now maturing on the trade/logistics/supply chain side, my own involvement being prime example of this. All of this is work in progress. :) 

I can't underscore enough how important input like this is to guide this repo in the right direction.

**Comment by VladimirAlexiev** [comment]
@nissimsan now that I know you are core in both repos, it's clearer in my head.

But shouldn't this task be in the other repo (or a sibling of it)? You JSONify uncefact stuff over there, and just reuse it over here?

**Comment by nissimsan** [comment]
@VladimirAlexiev the reason I think it better here is because of UN/CEFACTs traditional attitude: all terms must be UN/CEFACT terms, which isn't healthy for interoperability. 
We have a more pragmatic approach here in Trace. The combination (schema definition + _some_ terms from CEFACT, remaining terms from other established vocab) is super powerful.
