### ISSUE TITLE
Add example of ForeignChargeDeclaration

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#231]
I encountered a schema error with this field when converting to OAS 3.0

@nissimsan can you confirm this type and its example have been fixed?

**Comment by BenjaminMoe** [comment]
Still needs to be resolved.

**Comment by OR13** [comment]
Still needs to be resolved:
<img width="942" alt="Screen Shot 2022-07-05 at 1 08 54 PM" src="https://user-images.githubusercontent.com/8295856/177389420-4c119417-f422-4f10-8e23-df9e030eaca8.png">

**Comment by OR13** [comment]
Still needs to be fixed

![Screen Shot 2022-10-11 at 12 59 30 PM](https://user-images.githubusercontent.com/8295856/195165496-a084cc72-2acf-4d62-9a2b-1ffb0c75cabf.png)
