### ISSUE TITLE
Remove RevocationList2020Status or fix it

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#235]
Example is wrong and linked data annotation is wrong.

**Comment by OR13** [comment]
![Screen Shot 2022-02-15 at 1 19 12 PM](https://user-images.githubusercontent.com/8295856/154133247-3da6c23f-b1f8-4c95-b4ca-a7286ea6292f.png)


cc @nissimsan

**Comment by nissimsan** [comment]
Sure, I can take a look at this when I get some bandwidth. Can't we just copy the example from the revocation spec? ... Which logically leads to the point: why repeat what's in the revocation spec? I'm leaning towards removal...

**Comment by BenjaminMoe** [comment]
Needs to remove `issue`. Confirms still an open issue an example needs to be updated.

**Comment by OR13** [comment]
Seems fixed

![Screen Shot 2022-10-11 at 1 00 18 PM](https://user-images.githubusercontent.com/8295856/195165625-8baec999-aca8-4a7b-8e3b-564b6ead46b8.png)
