### ISSUE TITLE
Remove SCAC from generic BillOfLading

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#243]
SCAC appears to be a maritime only term, and does not apply to most BOL's, should probably be removed from the base BOL and added to a more specialized BOL.
https://github.com/w3c-ccg/traceability-vocab/blob/64db7340c5a64539cfea9e6ff2fb3a768e944f82/packages/traceability-schemas/schemas/BillOfLading.json#L43

**Comment by nissimsan** [comment]
SCAC are used throughout intermodal transport, not only maritime. 
https://en.wikipedia.org/wiki/Standard_Carrier_Alpha_Code

**Comment by OR13** [comment]
How do we move this along?

**Comment by nissimsan** [comment]
@mkhraisha, SCAC is a common identifier for carriers (incl land-based). This isn't a hill I'm ready to die on, but I think it would be wrong to remove it. Optional, for sure (which it is) - might that be the compromize? :)

**Comment by mkhraisha** [comment]
optional is fine by me.
