### ISSUE TITLE
Cleanup Development.md

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#244]
after PR #220 is added we will have a stale Development.md that will need to be rewritten.

**Comment by OR13** [comment]
Still needs to be done, see this dup as well https://github.com/w3c-ccg/traceability-vocab/issues/307

**Comment by BenjaminMoe** [comment]
Closing in favor of https://github.com/w3c-ccg/traceability-vocab/issues/307.
