### ISSUE TITLE
Questions regarding JSON Data Models for VCs

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#25]
Floating point number precision for CMTR fields should be 4 decimal places?

How is the traceability vocab related to SAP?

How is the traceability vocab related to Mulesoft?

we should set some default max lengths for strings.

max length for data uris, no image urls.

**Comment by OR13** [comment]
We need a section on "JSON Data Modeling" at the top of the spec that addresses this generally.

**Comment by mprorock** [comment]
> max length for data uris, no image urls.
@OR13 with no image urls how are you suggesting we handle bar code scan backups etc?  couple of ways to do this, but do you have a specific preference?  with ag items, we may also frequently need to link to an image of goods or samples as packed for another image related item - unless you mean something else here

**Comment by OR13** [comment]
@mprorock for small images... data uris will work... tracking pixels are a thing, adding anything to a VC that might result in a traceable outbound network request should be avoided when possible....

I think what is needed to close this issue out, is a section of JSON Data Modeling for VCs best practices at the top of the spec.

**Comment by mprorock** [comment]
@OR13 I have started on this - and agree, i think adding to the docs, with the ability to test VC creation are good and on the way. Are there any existing guides we should reference in the community?

**Comment by OR13** [comment]
IMO, this issue is not specific enough to be workable and should be closed... 

Suggest opening other issues for:

- Provide an example of a VC which contains image data.
- Add spec text warning to use strings instead of numbers for decimal representations.
etc...

**Comment by mprorock** [comment]
Agreed - later doc examples will arise from more detailed issues as they come up
