### ISSUE TITLE
Redundant country attributes on PostalAddress

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#253]
Is there a good reason for having two country definitions on PostalAddress? They seem redundant. 

```
  addressCountry:
    title: Address Country
    description: >-
      Code specifying the country (and country subdivision) for the address
      using ISO 3166-1.
    type: string
    $linkedData:
      term: addressCountry
      '@id': https://schema.org/addressCountry
```

```
  countyCode:
    title: County Code
    description: >-
      A code that identifies a county. A county is a territorial division in
      some countries, forming the chief unit of local administration. In the US,
      a county is a political and administrative division of a state.
    type: string
    $linkedData:
      term: countyCode
      '@id': https://gs1.org/voc/countyCode
```

**Comment by Fak3** [comment]
The one is countRy the other is county, they are different

**Comment by nissimsan** [comment]
@Fak3 , 
> The one is countRy the other is county, they are different
... I don't understand your point. So you're saying both are needed? When would you use one over the other? Or both at the same time? 

PS: Super happy to see you here, @Fak3!! :)

**Comment by Fak3** [comment]
> ... I don't understand your point. So you're saying both are needed? When would you use one over the other? Or both at the same time? 

A county is a territorial division in
      some countries, forming the chief unit of local administration.

**Comment by TallTed** [comment]
(Surprisingly enough, dereferencing the URIs found in the `'@id'` attribute of the `$linkedData` object -- <https://schema.org/addressCountry> and <https://gs1.org/voc/countyCode> -- reveals descriptions which I think are sufficient to answer the question.)

**Comment by nissimsan** [comment]
NOW I understand... Also what you meant by countRy, @Fak3. 
Thanks both - closing this.  :)

**Comment by VladimirAlexiev** [comment]
@nissimsan you still need to fix the documentation:
```
 addressCountry:
    description: >-
      Code specifying the country (and country subdivision) for the address using ISO 3166-1.
```
You prolly got that description from https://www.gs1.org/voc/addressCountry.
But that prop has some schizofrenia coming from its GDSN/EDIFACT legacy: is it a country or a country subdivision?
See https://github.com/gs1/WebVoc/issues/25

https://schema.org/addressCountry has no such schizofrenia:
- "The country. For example, USA. You can also provide the two-letter ISO 3166-1 alpha-2 country code."
- Which you'd be justified to make more definite: "The two-letter ISO 3166-1 alpha-2 country code."

**Comment by nissimsan** [comment]
Reopening this issue. It wasn't what the ticket was about, but @VladimirAlexiev's description is a big improvement, settling on ISO 3166-1 alpha-2 country code.

**Comment by nissimsan** [comment]
@VladimirAlexiev so really you're suggesting: keep `https://schema.org/addressCountry`, but restrict the description to "The two-letter ISO 3166-1 alpha-2 country code." (which is narrower than schema.org's definition). 
I love it - the idea of "US" vs "USA" incompatibility haunts me every time I see it. 
While I'd love to see a PR from you around here :) , I just made this: https://github.com/w3c-ccg/traceability-vocab/pull/282

**Comment by VladimirAlexiev** [comment]
@nissimsan and @OR13 I'll do some PRs. I'll start with LEI.
Can I add myself as "domain expert" for company data and LEI?

**Comment by OR13** [comment]
@VladimirAlexiev I am ok with a PR adding yourself, were you thinking of creating an LEI section here:

https://w3c-ccg.github.io/traceability-vocab/#introduction ?

**Comment by TallTed** [comment]
> the idea of "US" vs "USA" incompatibility haunts me every time I see it

While most of the non-USA "United States" have been renamed, so won't be confusing today, it's worth noting that "US" *could* refer to the United States of Venezuela, the United States of Brazil, the United States of Colombia, the United States of Ionian Islands, and others -- https://en.wikipedia.org/wiki/List_of_countries_that_include_United_States_in_their_name

**Comment by nissimsan** [comment]
@TallTed, our new and improved description clarifies this. In ISO 3166 context this is unambiguous:  https://en.wikipedia.org/wiki/ISO_3166-2:US

@VladimirAlexiev, assuming you have seen our schemas for the likes of https://w3c-ccg.github.io/traceability-vocab/#LEIentity ? Improvements are obviously very welcome!

I'll close this ticket again. It's far from the original (embarrassing) question I asked, and subsequent suggestions are PRed already.
