### ISSUE TITLE
Separate Context for Shipping/Logistics use case?

### ISSUE THREAD

**Issue by bumblefudge** [w3c-ccg/traceability-vocab#26]
Is there any objection to using a separate context that overlaps very little or not at all with that of the materials-tracking use-cases? Since there is so much semantic alignment happening in other venues on logistics, international shipping and trade, we would ideally like to focus our interoperability in that direction. My colleague Burkhard will be opening an issue later this week with input documents or links about that alignment, but I figured I should make a procedural issue first in case we were barking up the wrong tree.

**Comment by OR13** [comment]
This is a good question. I think we should avoid splitting contexts for as long as humanly possible. I am pretty strongly against separating JSON-LD contexts, and believe we should work together to make this vocab and a single context work for everyone :)

This will mean helping with things that may not directly benefit your use case.

**Comment by OR13** [comment]
@bumblefudge I would like to close this issue.
