### ISSUE TITLE
Bill of Lading must have description of cargo

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#267]
https://w3c-ccg.github.io/traceability-vocab/#BillOfLading has to include basic cargo description. A BOL without cargo description doesn't make any sense.

**Comment by nissimsan** [comment]
Once updated, add cargo descr. to Manifest example too.

**Comment by nissimsan** [comment]
Still pending.

**Comment by OR13** [comment]
Example and schema need to be updated... include an image as well.

**Comment by BenjaminMoe** [comment]
@nissimsan can we follow up on this?

**Comment by jmmski** [comment]
@BenjaminMoe - is it OK if I add some feedback on the schema and can give an example of a generic BOL?  Can I suggest a location in the schema to place it, also?

**Comment by nissimsan** [comment]
@jmmski absolutely! 

Note that we have other types such as `MasterBillOfLading`, `DCSATransportDocument`, `IATAAirWaybill` all of which have much more details. Might be useful for inspiration. 

The tricky question (I think) is "what is generic"? For example, containerization can't be assumed. Looking forward to seeing your stuff! Thank you!
