### ISSUE TITLE
Support for UN CEFACT

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#27]
- https://service.unece.org/trade/uncefact/vocabulary/uncefact/
- https://edi3.org/specs/edi3-json-ld-ndr/main/#json-ld

We may want to support it, but we need to comprehend how it relates to EPCIS, GS1, and other vocabs.

**Comment by nissimsan** [comment]
Note, edi3.org is an informal project code name and site. The formal UN/CEFACT name is RDM2API. Similarly, the official link to the vocabulary which is the output of this project is here: 
https://service.unece.org/trade/uncefact/vocabulary/uncefact/

**Comment by OR13** [comment]
I think the next steps for this would be to find the best possible "EDI3" example to add as a first pass... ideally something very small and highly valuable

**Comment by OR13** [comment]
We've seen related issues with gs1 unitCode... we would like to see a "better exampl" on the issue, and work towards a PR.

**Comment by OR13** [comment]
This is in progress, stay tuned for a PR. @nissimsan to cross link when you have a PR to review.

**Comment by nissimsan** [comment]
https://github.com/w3c-ccg/traceability-vocab/pull/200 has links into the UN/CEFACT vocab.

**Comment by nissimsan** [comment]
Blocked by https://github.com/w3c-ccg/traceability-vocab/issues/207

**Comment by nissimsan** [comment]
The blocker is long gone. We do have relevant references to UN/CEFACT now. We can close this.
