### ISSUE TITLE
fix LEIauthority

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#274]
Look at the diagram in #272, which shows a LEI L1 sample graph. I assume that [LEIauthority.yml](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/LEIauthority.yml) is intended to represent the middle `(I)` node on that diagram.

Current representation:
```
  {
    "type": "LEIauthority",                               -> traceability:LEIauthority
    "validationAuthorityID": "RA000004",                  -> schema:identifier
    "otherValidationAuthorityID": "I9LWK4HR",             -> schema:taxID
    "validationAuthorityEntityID": "IR6TTVJ948RGX9YQDM4V" -> schema:leiCode
  }
```

I think it needs to be corrected as follows:
```
  {
    "type": "LEIRegistryIdentifier",      -> gleif-L1:BusinessRegistryIdentifier                        (1)
    "validationAuthorityID": "RA000004",  -> traceability:leiRalCode or gleif-L1:hasRegisteredAuthority (2)
    "nationalEntityID": "I9LWK4HR",       -> gleif-L1:hasEntityID                                       (3)
                                                                                                        (4)
  }
```
1. This record is not an "authority" but a national business registry identifier (that was used for corroboration: `hasValidationIdentifier`)
2. I think a new data prop `traceability:leiRalCode` is needed because:
   - `gleif-L1:hasRegisteredAuthority` is an object property so can't be used with literal (eg "RA000004")
   - `gleif-base:hasTag` is too unspecific to use here (@rivettp do you agree?)
   - Note: I've created the Wikidata prop [P9487](https://www.wikidata.org/wiki/Property:P9487) "RAL code"  and imported a bunch of values
3. "otherValidationAuthorityID" is completely wrong here, I think you swapped it with "validationAuthorityEntityID". 
   - `gleif-L1:hasEntityID` from the GLEI ontology is a good name, so I mapped to it
   - `schema:taxID` is not always correct because some of the RAL are not tax registries (but eg registers of financial institutions, foundations, insurers, etc)
   - IMHO the term `nationalEntityID` is nicer (shorter) than `validationAuthorityEntityID`. But if you consider the latter more precise (paralleling `validationAuthorityID`) then use that
4. I've removed the last line because:
   - There is [gleif-L1:hasOtherAuthority](https://www.gleif.org/ontology/v1.0/L1/index-en.html#hasOtherAuthority) "A legacy / historical reference code of a registration authority which is not yet entered in the Registration Authorities Code List (RAL) maintained by GLEIF" but now all national authorities are in RAL, so that's not populated. 
   - Not all authorities have LEI (unlike the LOUs that issue LEIs, as you can see in the right `(I)` node)
   - There's no connection between RAL and LEI of authorities in the data (i.e. we don't know the LEI of US-DC's "DCRA", if any)

**Comment by OR13** [comment]
@VladimirAlexiev I think you are correct. Happy to take a PR to make the change.

It is not our intention to do anything other than use the latest gleif ontology terms.

We are only trying to explain how to map to them for "JSON Schema" types defined here.

**Comment by VladimirAlexiev** [comment]
I like gleif-L1:hasRegisteredAuthority but it's an object prop whereas RAL code is a data prop. Let's see what Pete says

**Comment by TallTed** [comment]
@VladimirAlexiev -- Maybe tag Pete via github handle?

**Comment by nissimsan** [comment]
@VladimirAlexiev, can we ask you to spell out precisely what needs to be done to resolve this? What would a PR look like which fixes this?

**Comment by OR13** [comment]
Suggest we close this due to inactivity.

**Comment by brownoxford** [comment]
Inactive, closing now.

**Comment by VladimirAlexiev** [comment]
@OR13 or @brownoxford can you reopen and assign to me?

**Comment by OR13** [comment]
@VladimirAlexiev How do you plan to address this issue?

What information do you need before this is ready for PR, or how will a PR address this issue?

**Comment by BenjaminMoe** [comment]
@VladimirAlexiev any updates on this?

**Comment by nissimsan** [comment]
@VladimirAlexiev, do you still want to progress this? If not we'd like to close it off.

**Comment by nissimsan** [comment]
Stale, closing
