### ISSUE TITLE
AgProduct has many props not specific to Agriculture

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#278]
[AgProduct.yml](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/AgProduct.yml):
- has a bunch of props not specific to Agriculture:
  `upc plu gtin labelImageUrl labelImageHash`
  - These should be moved to `Product`. Or if for some reason they don't belong in `Product`, make a new subclass `IdentifiedProduct` 
- has only 1 prop specific to Agriculture: `scientificName`.
  Shouldn't it have more, eg related to: lot/batch number, protected geographic origin, freshness, etc?

**Comment by OR13** [comment]
Suggest we move these terms to an RDF class that is not agriculture specific.

**Comment by OR13** [comment]
cc @brownoxford

**Comment by OR13** [comment]
cc @rhofvendahl

**Comment by BenjaminMoe** [comment]
Assigning @rhofvendahl

**Comment by nissimsan** [comment]
Ping @rhofvendahl  and @brownoxford .

**Comment by OR13** [comment]
Still ready for PR, Ping @rhofvendahl and @brownoxford .

**Comment by nissimsan** [comment]
Can we close this? 

Please.

**Comment by nissimsan** [comment]
Pending close due to inactivity.
