### ISSUE TITLE
remove EAN/UPC in favor of GTIN

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#281]
[AgProduct.yml](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/common/AgProduct.yml) has a prop mapped to https://www.gs1.org/standards/barcodes/ean-upc.

However, that's a web page not a property definition.

- You won't find "EAN" or "UPC" at https://www.gs1.org/voc/
- https://schema.org/gtin13  "equivalent to 13-digit ISBN codes and EAN UCC-13. Former 12-digit UPC codes can be converted into a GTIN-13 code by simply adding a preceding zero"
- https://schema.org/gtin8 "also known as EAN/UCC-8 or 8-digit EAN"

So you see that EAN/UPC is just an old name for `gtin`.

Note: `schema` distinguishes between `gtin8, gtin13` and their super-property `gtin`.
`gs1:` and `traceability` have only one prop `gtin`.
IMHO there's no need for two since you can examine the value to see whether it's 8 or 13 digits long.

**Comment by OR13** [comment]
@nissimsan @BenjaminMoe please comment.

**Comment by nissimsan** [comment]
@mprorock , @brownoxford , this seems to be one of "yours"?

**Comment by paulfdietrich** [comment]
This is what I am hearing from our experts at GS1.   UPC does not have a GS1 vocabulary since UPC is an industry term and not a GS1 standard like GTIN. When folks say UPC they are often referring to a GTIN-12. The GTIN vocabulary element already included conveys the proper information for agriculture and the UPC field is not required. Care must be taken to ensure that industry users looking for UPC should reference the GTIN field for a GTIN-12. Hope this helps.

**Comment by nissimsan** [comment]
@rhofvendahl to look into this still.

**Comment by OR13** [comment]
Not ready for PR, needs refinement. suggest pending close as stale

**Comment by OR13** [comment]
We think its possibly stale, ping @rhofvendahl

**Comment by nissimsan** [comment]
@rhofvendahl, 
https://w3c-ccg.github.io/traceability-vocab/#PlantSystemsInspectionCredential
has 
```
        "upc": "033383401508",
        "plu": "94225",
        "gtin": "033383401508",
```

**Comment by rhofvendahl** [comment]
@nissimsan Can't seem to find that. Are you looking at the latest from https://github.com/w3c-ccg/traceability-vocab/pull/863?

[Here's](https://github.com/w3c-ccg/traceability-vocab/blob/0e7936434a0c251bf0257fb27fca291b3e852767/docs/openapi/components/schemas/credentials/PlantSystemsInspectionCredential.yml) the file from that branch

**Comment by nissimsan** [comment]
@rhofvendahl did this
