### ISSUE TITLE
Elaborate section #vocabulary-linkage

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#287]
Looking at the JSON schemas:
- I saw big chunks from DCSA EBL, IATA AirWayBill, schema.org
- Smaller chunks from gs1.org/voc, USDA, US Border Protection...

The diagram in https://w3c-ccg.github.io/traceability-vocab/#vocabulary-linkage is nicely illustrative, but it doesn't show the full picture.

Expand that section to describe:
- all reused vocabularies, 
- term stats: (at least approximate) number of reused classes and props; and same for Traceability own terms

Why bother:
- as an ontologist, the first thing I evaluate when I stumble upon a schema or ontology, is its scope: what does it cover, what are the counts?
- then I look at provenance: have these guys looked at existing schemas? or did they set out to reinvent the wheel?
- promoting reuse is always a good thing.

Example: http://www.semantic-web-journal.net/system/files/swj2616.pdf p14:
![image](https://user-images.githubusercontent.com/536250/151378535-8607ba6d-21de-49ca-86dd-82e72427f27d.png)

**Comment by VladimirAlexiev** [comment]
@OR13 @nissimsan these days I'm constantly mistyping #transparency (https://transparency.entsoe.eu/, https://www.ontotext.com/knowledgehub/current/tekg-project/) and #traceability :-)
Tweet: https://twitter.com/valexiev1/status/1486706797826088964

**Comment by OR13** [comment]
@VladimirAlexiev I think you pretty much nailed our intention here... our execution is still improving.

**Comment by nissimsan** [comment]
Very happy that you like this section, @VladimirAlexiev, and we can definitely expand it. 

The diagram isn't intended for the "as an ontologist" persona and shouldn't be overloaded with a full picture. But generating a table should be doable and worthwhile for building credibility and proving our intention that we reuse before inventing. The ratio of https://w3id.org/traceability (invent) versus others (reuse) would be interesting to follow.

**Comment by OR13** [comment]
We should list ontologies better, I agree. I think this is ready for PR.

**Comment by nissimsan** [comment]
@VladimirAlexiev, have you seen this:
https://w3c-ccg.github.io/traceability-vocab/#ontology-visualizations

I think that's largely what you are asking for (although not in table form). 

I'd say we can close this.

**Comment by BenjaminMoe** [comment]
Marking as done, re-open if needed.
