### ISSUE TITLE
Consider using LinkML

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#295]
@OR13 @nissimsan 
For both Traceability, Edi3, Uncefact you use JSON Schema (plus a bit) as your modeling language.

But that's not enough because it leaves a lot of the semantic aspects loose.

Before trade & logistics had heard of semantics, life science people were doing massive cross-institutional semantic KGs. So check this out:

https://linkml.io/
https://github.com/linkml
Google "linkml" in particular see berkeleybop video etc

Last time I looked (1y ago) it was called BioLinkML and had peculiarities for their case. I think this had now been generalized.

-------

Another option could be hackolade.com. It's commercial and doesn't yet have RDF stuff but explains very well the ideas of Polyglot Storage (or Polyglot Persistence)

**Comment by nissimsan** [comment]
LinkML looks awesome!

**Comment by VladimirAlexiev** [comment]
https://linkml.io/linkml/intro/overview.html#we-eat-our-own-dogfood is pretty convincing: it's good enough to describe itself
