### ISSUE TITLE
consider Allotrope data model for advanced Measurements

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#297]
@OR13 asked (at the QUDT repo? paraphrasing)
> where can I find units and features for things like Hardness test?

The state-of-the-art for advanced lab equipment measurements are the Allotrope data models. These include Tensile strength tests, Hardness tests, NMR, spectrography, and a big bunch of others that are beyond my understanding.

These represent metadata (instrument, analyst, run, conditions etc), data cube definitions (extending W3C CUBE) and mapping to HDF5 for large and complex numeric arrays.

- https://www.allotrope.org/product-releases: data models (ASM's)
- https://www.allotrope.org/solution
- https://www.allotrope.org/allotrope-framework
![image](https://user-images.githubusercontent.com/536250/152035364-ff9afd8c-f730-4e2f-8d62-e44a85c28851.png)
- presentations: https://www.allotrope.org/resources (I watched several https://www.allotrope.org/october-2019-allotrope-connect, v.nice)
- ontology releases as zip: https://www.allotrope.org/ontologies
- ontologies as resolvable URLs: http://purl.allotrope.org/
- docs: eg https://docs.allotrope.org/ADF%20Data%20Cube%20to%20HDF5%20Mapping%20Ontology.html
- other resources incl source code and examples require **gitlab** login (I got one and asked them for access but haven't sorted it out yet)

**Comment by VladimirAlexiev** [comment]
Pros
- **the** standard in the sciences and lab measurements
- can represent large data cubes (numeric arrays, incl complex data cubes) that it wouldn't make sense to represent in JSON or RDF

Cons:
- learning curve

**Comment by nissimsan** [comment]
Still pending a volunteer to pick this up.

**Comment by OR13** [comment]
Could use a JSON-LD example to make this more actionable.

**Comment by nissimsan** [comment]
Still pending volunteers. The suggestion is still valid.

**Comment by mkhraisha** [comment]
No volunteers for this action item have come forward, will be closing the issue due to lack of interest.
