### ISSUE TITLE
visualization guide

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#306]
> https://rdf2svg.redefer.rhizomik.net/
> https://rhizomer.rhizomik.net/

https://lists.w3.org/Archives/Public/semantic-web/2022Feb/0029.html

**Comment by nissimsan** [comment]
Additional visuals: 
- List of vocabs used
- List of schema warnings

**Comment by mkhraisha** [comment]
A tool i found very helpful would be this: http://vowl.visualdataweb.org/webvowl.html 
you can view a sample with the one record ontology here https://onerecord.iata.org/ontology/webvowl/index.html#

**Comment by nissimsan** [comment]
The main thing I'm after is pretty simple - a third pie/bar chart (along with the ones above) which tell me: 
- There is a **total** of 2000 terms defined on this repo
- 900 of them are referencing **https://schema.org** 
- 700 of them are referencing **https://service.unece.org**
- 500 of them are referencing **https://w3id.org/traceability**
- 100 of them are referencing **https://voc.gs1.org**

**Comment by nissimsan** [comment]
I'll make a new issue for my request.
