### ISSUE TITLE
 Consignment Rating Details, itemized consignment items of IATA Air Waybill. 

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#308]
![Screen Shot 2022-02-15 at 1 23 46 PM](https://user-images.githubusercontent.com/8295856/154133944-5b1d202f-ac99-4aec-9a0f-8d73605781fb.png)

**Comment by OR13** [comment]
What should be shorten this sentence too? @nissimsan

**Comment by nissimsan** [comment]
Oh, looks like I've goofed up title and description there...
I'll action it quickly.

**Comment by nissimsan** [comment]
Done
