### ISSUE TITLE
References

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#309]
Hi folks, 
How do I make references like the single one we have listed here?
https://w3c-ccg.github.io/traceability-vocab/#informative-references

**Comment by OR13** [comment]
You need to update the index.html files like so:

https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/index.html#L149

Or use this syntax

https://github.com/w3c/did-spec-registries/blob/main/index.html#L93
https://github.com/w3c/did-spec-registries/blob/main/index.html#L197

**Comment by OR13** [comment]
if these answers are sufficient please close this issue
