### ISSUE TITLE
Replace GS1 Place with Schema.org Place

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#31]
For any term where GS1 just copied schema.org, we should use schema.org definition instead.

For example:

https://www.gs1.org/voc/Place -> https://schema.org/Place

**Comment by OR13** [comment]
@mprorock @mkhraisha can one of you tackle this as a way of getting used to contributing here?

**Comment by mprorock** [comment]
@brianwmunz from our team is tacking this I believe as part of #32 - this is also related to #24

**Comment by mkhraisha** [comment]
@mprorock @brianwmunz I'd happily tackle this next week if you would don't have the bandwidth.

**Comment by mprorock** [comment]
@mkhraisha that should be fine - may want to check with @brianwmunz (let me know if you need his work email - I believe he is using this model moving forward with our new schema objects, e.g. AgInspection and related

**Comment by mkhraisha** [comment]
@mprorock  sorry I didn't follow your last comment, is @brianwmunz working on this already or should I tackle it?

**Comment by mprorock** [comment]
@mkhraisha is certainly handling a good example of this - but we likely need to do some more cleanup - and make the decision on "place" specifically.  that one is likely worth keeping in as a vc example, even though it is redundant.  all our commits going forward will be linking back out to gs1, schema.orgm etc.  @OR13 are you still of the opinion we keep place in for example purposes?

**Comment by OR13** [comment]
IMO, we should keep Place / PostalAddress / GeoCoordinates, because they are fundamental to traceability...

**Comment by brianwmunz** [comment]
Sorry I missed some of your comments on here @mkhraisha but I've just submitted a PR for these changes.
