### ISSUE TITLE
DEVELOPMENT.md#ontology-structure should be changed to YAML example

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#311]
This still shows our earlier JSON ways:
https://github.com/w3c-ccg/traceability-vocab/blob/main/DEVELOPMENT.md#ontology-structure

**Comment by BenjaminMoe** [comment]
I think this is effectively a duplicate of: https://github.com/w3c-ccg/traceability-vocab/issues/307
