### ISSUE TITLE
Start versioning

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#313]
https://w3c-ccg.github.io/traceability-vocab/ 
**Traceability Vocabulary v0.0** feels immature. We may have a long way to go still, but surely we're beyond v0.0. Can we start the counter somehow? Or at the very least just manually bump it to v0.1.

**Comment by BenjaminMoe** [comment]
![Screenshot 2022-03-18 at 23-24-11 Traceability Vocabulary v0 0](https://user-images.githubusercontent.com/86194145/159021129-d89deb00-b0d1-47ae-9042-8c05b7c08111.png)

I agree, and find the label of **v0.0** confusing. Set value from CI. Ex: **CI: bumps version to v1.13.0 **

**Comment by nissimsan** [comment]
What versioning approach would we want to take on this?

**Comment by nissimsan** [comment]
Suggestion: PR to bump respec to v1.0

**Comment by BenjaminMoe** [comment]
Suggest update document to v0.1.

**Comment by BenjaminMoe** [comment]
@mkhraisha will do the PR

**Comment by mkhraisha** [comment]
Merged in #713
