### ISSUE TITLE
Redundancy with Schema.org

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/traceability-vocab#32]
In creating new schemas for the AgInspectionReport, I noticed that in the current repo, we have schemas that are not modified or extended (as far as I can tell) from the ones they reference on GS1 or schema.org.  Why is that?  Shouldn't we simply ref out to Place, for example, rather than having it in the repo?

**Comment by mprorock** [comment]
definitely should be referenced outbound wherever possible - if however an item is the root object for a VC we may want to include it in the repo (or in the case of place, being used as an example for issuing a VC) - @OR13 Thoughts?

**Comment by OR13** [comment]
For some things like Place, it feels like its worth showing them in this vocab, even if they are just linking through to Schema.org...

The goal is to provide a vocabulary for verifiable credentials in a single context, and since we generate that context from schemas and test code, there is a certain amount of verbosity / redundancy we are required to implement, but the semantics are coming from schema.org, not from us.

I think we all need to agree on thing like "PostalAddress" and "Place"... IMO they are worth keeping in both the context and the documentation... but I am not sure I would pull in "Person" or "Organization, certainly not in their entirety.... 

I think what is really needed are some examplar VCs which demonstrate the balance we are looking for.

**Comment by mprorock** [comment]
@OR13 i think you are right on the VC examples. @brianwmunz is currently adding one for AgInspection that should set a good balance.

**Comment by brianwmunz** [comment]
@OR13 and @mprorock I've checked in the AgInspection stuff, so please take a look and see what you think about the balance between what to pull from schema and what to ref to.  I will say that something to keep in mind is that linking out to schema.org isn't just a philosophical decision, it would require some changes within the schema and VC testing to enable those references.  I'll hold off on making an issue on this because we haven't decided which way to go.

**Comment by OR13** [comment]
@brianwmunz I am not sure what you mean by "linking out".... we def don't want to be downloading 100% of schema.org to test a few terms. 

essentially, we build `traceability-v1.jsonld` from some JSON Schemas and then we generate the spec from these.

the spec should reflect that all terms defined in `traceability-v1.jsonld` have human readable definitions, and those should be clickable links to schema.org or elsewhere.

I am wondering if we have sufficiently addressed this issue as of the latest changs.

**Comment by brianwmunz** [comment]
Yeah perhaps not the best wording by me, but I think this is what we've been talking about for a little while.  Basically to boil down the question...if we want to have Person in our schema for example, what should be the proper way?  The testing suite we have now doesn't have a way (that I can tell) to have Person not live locally in some part without there being a Context error.

**Comment by OR13** [comment]
@brianwmunz good example, imo `Person` and `Organization` are good classes for us to demonstrate how to accomplish this.

There should be some JSON Schemas for each, and those should reference schema.org... I would expect the JSON schema to be a subset of the allowed fields visible on schema.org.

**Comment by OR13** [comment]
i think this issue can be closed once we have a few examples of how this vocab works with schema.org

**Comment by brianwmunz** [comment]
> There should be some JSON Schemas for each, and those should reference schema.org... I would expect the JSON schema to be a subset of the allowed fields visible on schema.org.

To be clear, do you mean that we should create these schemas within the repo and only pull in the fields that we think are relevant to the vocab schemas?

**Comment by OR13** [comment]
@brianwmunz yes, for example:

Person.json -> a json schema describing a person and all the semantic properties we care about for traceability imported from schema.org (which defines their IRIs).

When the traceability-v1.jsonld is generated, it would contain only the subset of JSON members which we defined in JSON Schema, but their definitions would remain defined by schema.org.

this is the approach we have already taken form `Place` and `PostalAddress`.
