### ISSUE TITLE
Data modeling convensions

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#324]
I would appreciate if we can agree to some data modelling conventions. Primarily whether we should discourage/disallow elements at root level outside of the VC data elements (credentialSubject, issuer, etc)? 

1. One convention might be"any XxxCertification must always have a corresponding Xxx class which defines its credentialSubject, and all data elements should be included there. An example of this would be including the `carrier` organization on a bill of lading, although it is also the issuer of the VC. 
2. Alternatively, a convention could be to encourage defining credentialSubject to be as focused as possible, and keep other "peripheral" data at root level. For example, a CertificateOfOrigin would have just the certified goods as credentialSubject, and keep elements like originCountry at the VC's root-level. 
3. It's also an option to not do any such conventions and decide on a case-by-case basis.

**Comment by nissimsan** [comment]
@mkhraisha, this is what we discussed last Tuesday.

**Comment by nissimsan** [comment]
Somewhat philosophically, this is also a question of whether the VC _is_ the document, or rather if it is some layer _on top of_ the document. 

I personally find it abstract to wrap my head around what a BillOfLading is, if it isn't the BillOfLadingCertificate. I have nothing to relate it to.

**Comment by mkhraisha** [comment]
I believe 1. makes the most sense to me. It helps keep the "VC stuff" separate from the "business stuff" and makes it much easier for me to reason about. 

> There would be a nice consistency in just demanding that XxxCertification always targets a Xxx class. But it does feel like we're introducing excess classes for no actual reason.
I think this doesn't make sense as a restriction, as sometimes a Certificate is an amalgamation of multiple smaller types, like an organization, a product etc.

**Comment by nissimsan** [comment]
I think I missed a 4th option. Same as 1., the XxxCertificate always only targets dedicated schemas for `credentialSubject` and `issuer`, nothing else "floating around". But without the strict name binding (`XxxCertificate.credentialSubjest: {type: Xxx}`). 

Continuing with the BillOfLading example is a perfect candidate: a VC about a Consignment ([UN/CEFACT](https://service.unece.org/trade/uncefact/publication/Transport%20and%20Logistics/MaritimeBill/HTML/001.htm)): 

![image](https://user-images.githubusercontent.com/34443212/157243456-b06f3e3c-4b4a-4eec-8964-125bfeed9c05.png)

**Comment by OR13** [comment]
See https://github.com/w3c-ccg/traceability-vocab/blob/gh-pages/contexts/traceability-v1.jsonld#L7

The current context has a number of "top level properties".

```
    "name": "https://schema.org/name",
    "description": "https://schema.org/description",
    "identifier": "https://schema.org/identifier",
    "image": {
      "@id": "https://schema.org/image",
      "@type": "@id"
    },
    "relatedLink": {
      "@id": "https://w3id.org/traceability#LinkRole"
    },
```

EVERY verifiable credential can have this term in its top level verifiable credential.


For example:

```
 "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://w3id.org/traceability/v1"
  ],
  "id": "https://example.com/credential/123",
  "type": [
    "VerifiableCredential",
    "MillTestReportCertificate"
  ],
  "name": "Certified Mill Test Report",
  "description": "This document includes recommended mill certificate fields.",
  "relatedLink": [
    {
      "type": [
        "LinkRole"
      ],
      "target": "https://www.example.com/template/123",
      "linkRelationship": "templateLink"
    }
  ],
  "issuanceDate": "2019-12-11T03:50:55Z",
  "issuer": {
```

**Comment by nissimsan** [comment]
Agreement to keep claims credentialSubject, not on the root VC.
