### ISSUE TITLE
How can I add citations?  

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#327]
Can anyone tell me how to add citations, pls? Both referencing from schema descriptions and also from https://w3c-ccg.github.io/traceability-vocab/ ?

**Comment by TallTed** [comment]
This is a [ReSpec thing](https://respec.org/docs/#references).

It seems likely you'll need to [ask Specref to add the external docs](https://respec.org/docs/#adding-missing-references).
