### ISSUE TITLE
Readme process for build and testing

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/traceability-vocab#33]
I'm wondering at which point in the described process the test-vectors files are created in the docs folder.  Based on the readme, in order to properly contribute, the developer needs to create a JSON schema, create a synthetic data gen file, and run the tests.  Is this when the build happens to create the test-vectors file for the new vocab or is there a separate call that isn't listed? 
I've attempted to run the process with the simplest file I could create and it always fails due to the docs/test-vectors file having not been generated.

**Comment by mprorock** [comment]
@OR13 any insight on this?

**Comment by mkhraisha** [comment]
hasn't this been addressed by #30 ?

**Comment by brianwmunz** [comment]
I think a step may be missing from the Readme which builds the test-vectors.

**Comment by OR13** [comment]
@brianwmunz I have added instructions, can you run through them and close this issue, propose new changes that are needed here, or open a PR which implements them?

**Comment by brianwmunz** [comment]
I think the addition of a reference to the new schema to the config.js file in [./packages/test-vectors/src/generators](https://github.com/w3c-ccg/traceability-vocab/tree/main/packages/test-vectors/src/generators) and the index.js file in [./packages/test-vectors/src/__fixtures__](https://github.com/w3c-ccg/traceability-vocab/tree/main/packages/test-vectors/src/__fixtures__) is missing in the documentation.  I'll make these changes and submit a PR once we can resolve issue #35 and ensure the whole process is captured.

**Comment by OR13** [comment]
I left a comment on #35
