### ISSUE TITLE
PurchaseOrder and Purchase should be linked

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#336]
Purchase references a purchaseOrder field, which is defined as an identifier. It should be updated to either be:
* purchaseOrderID 
or 
* reference the PurchaseOrder Schema

#323 Purchase order was added to

**Comment by BenjaminMoe** [comment]
Okay, I see what you mean here. Because the term is overlapping, we need to be very specific about what the relationship is. In my experience a purchase will refer back to the id of a purchase order, so `purchaseOrderID` as an array of strings.

**Comment by TallTed** [comment]
Just as a Purchase Order may be issued without a Purchase taking place (as with the late delivery described in #323), a Purchase may take place without a Purchase Order (such as when a staff member makes an immediate Purchase through a cash register and expenses it later).  So, while Purchase and Purchase Order should have fields that allow for cross reference, both directions should be optional.

**Comment by BenjaminMoe** [comment]
I think this has been addressed with PR #345. Closing and can be re-opened if needed.
