### ISSUE TITLE
Add `openapi.yml` to gitignore

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#337]
To avoid it causing further merge conflicts

**Comment by HritikR** [comment]
Hi @nissimsan, Can you please assign this to me?

**Comment by nissimsan** [comment]
For sure, @HritikR. 
While you're at it, please gitignore `packages/traceability-schemas/data/credentials` and `packages/traceability-schemas/data/credential.verifiable.json` too. 
Thanks!
