### ISSUE TITLE
Update Use Cases and Requirements Section

### ISSUE THREAD

**Issue by aniltj** [w3c-ccg/traceability-vocab#34]
Update the current section to provide insight and information on the work that is currently being covered, with the entities that are focused on those areas filling in more details.

Proposed starting point for the language:

_This section is non-normative._

The following use cases outline a number of key scenarios that readers might find useful:

- Supply Chain Traceability of Steel
- Supply Chain Traceability of Oil
- Supply Chain Traceability of Food
- Supply Chain Traceability of Natural Gas
- Supply Chain Traceability of Direct-to-Consumer E-Commerce Shipments

**Comment by mprorock** [comment]
Picking up the Food/Ag side of this for use case details, etc. @aniltj do we want updates to both the docs and readme here? it seems like both should be cleaned up a bit

**Comment by aniltj** [comment]
@mprorock I believe so, but defer to all of you on the specifics. I was just reading that section and it simply mentioned mill test certs and I know that you all are working on more than that. Would be good to reflect the reality for folks who show up.

**Comment by mkhraisha** [comment]
Oil and Gas are done via #40 

pending use cases are: Supply Chain Traceability of Direct-to-Consumer E-Commerce Shipments

**Comment by bumblefudge** [comment]
Terribly sorry, not sure how I missed this. Addressed with [pr66](https://github.com/w3c-ccg/traceability-vocab/pull/66)

**Comment by mprorock** [comment]
Still some room (as always) to improve docs, but with pr #66 and #68 I think we are now covered.
