### ISSUE TITLE
First time test-vector generation

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/traceability-vocab#35]
After creating a new schema, following the steps, and running the tests, the tests fail and are expecting a file in the docs/test-vectors directory.  Does this file need to be created manually the first time?  How does the initial generation run?
Thanks
@OR13 @mprorock

**Comment by OR13** [comment]
I think you need to create a file like this: 

https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/test-vectors/src/generators/Place.js

Then this file https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/test-vectors/src/generators/generate.test.js

Will generate the test vector automatically, using the values registered in: https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/test-vectors/src/generators/config.js

I think this all needs to be documented better.

**Comment by brianwmunz** [comment]
These are the steps I've taken so far, but I get errors.  Let me do some further debugging.

**Comment by brianwmunz** [comment]
Figured it out and the process isn't the most straightforward, but I'll update the readme with the current way of doing things then open an issue to change the test script to do it programmatically.  Then I, or anyone who wants to contribute can make that change later.

**Comment by OR13** [comment]
@brianwmunz thanks!, feel free to open issues describing how you wish it were, I expect we will need to take a couple passes on this before its a smooth start.

**Comment by brianwmunz** [comment]
@OR13 We're thinking of adding a build process which sets an env variable to generate the files for new schemas.  I should be able to submit a PR on that in in the next day or so.

**Comment by OR13** [comment]
yes, we could set it up as npm commands with `BUILD_SPEC=true npm run test`
