### ISSUE TITLE
Sample E-Commerce workflow missing links to credentials in description

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#351]
https://w3c-ccg.github.io/traceability-vocab/#sample-e-commerce-workflow

![Screenshot 2022-10-24 8 59 52 PM](https://user-images.githubusercontent.com/86194145/197520853-003b0b35-d681-49be-96f4-18c61bbf880d.png)

Text provided for sample ecommerce workflow. Should provide links to Credentials schemas for documents described.

**Comment by nissimsan** [comment]
Thanks.

**Comment by BenjaminMoe** [comment]
Fixed. Closing.
