### ISSUE TITLE
Add Example to JWS Test Suite.

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#353]
https://github.com/decentralized-identity/JWS-Test-Suite/issues/18

**Comment by nissimsan** [comment]
This is still pending.

**Comment by OR13** [comment]
I suggest we revise this to track the W3C VCWG tests instead of the DIF repo test suite.

**Comment by OR13** [comment]
We should discuss adding support for VC-JWT 2.0 and its ability to support securing `credential+ld+json` or whatever media type the VCWG defines, with JWT and CWT.... we have no timeline for that work.

vc-jws-2020 has been withdrawn, see: https://github.com/w3c/vc-jws-2020/pull/33
