### ISSUE TITLE
Fix schema syntax errors in Credentials

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#358]
From: https://github.com/w3c-ccg/traceability-vocab/pull/355

**Comment by BenjaminMoe** [comment]
Update for schemas that need to be fixed to appear in openapi:

- CrudeOilProduct
- ImmediateDelivery
- ImmediateDeliveryCertificate
- ImmediateDeliveryLineItem
- InvoiceRegistrationEvidenceDocument
- MultiModalBillOfLadingCertificate
- NaturalGasProduct
- OrderRegistrationCredential
- OrderRegistrationEvidenceDocument
- PGAStatusMessageCertificate
- PackageItem
- PackageRegistrationCredential
- PackingListCertificate
- PackingListItem
- PackingListRegistrationCredential
- ProductReceiptRegistrationCredential
- ProductRegistrationCredential
- ProformaInvoiceCertificate
- PurchaseOrderCertificate
- RevocationList2020Status
- SIMASteelImportLicenseApplicationCertificate
- SIMASteelImportLicenseCertificate
- SeaCargoManifest
- SeaCargoManifestCertificate
- ShippingInstructionsCertificate
- SoftwareBillOfMaterialsCertificate
- TransferEvent
- TransformEvent
- TransportEvent

**Comment by TallTed** [comment]
If I understand the point of [this list](https://github.com/w3c-ccg/traceability-vocab/issues/358#issuecomment-1101984403) correctly, perhaps it should be switched from bullets to checkboxes?

**Comment by BenjaminMoe** [comment]
> If I understand the point of [this list](https://github.com/w3c-ccg/traceability-vocab/issues/358#issuecomment-1101984403) correctly, perhaps it should be switched from bullets to checkboxes?

Updated to checkboxes.

**Comment by BenjaminMoe** [comment]
I think this issue can be closed. We should continue refine and fix syntax errors as we find them, but the original purpose for this issue has been concluded.
