### ISSUE TITLE
Map Events to EPCIS definitions

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#370]
The Event types of https://github.com/w3c-ccg/traceability-vocab/pull/362 etc seem to reflect EPCIS. Might we map to their terms directly? 
https://github.com/gs1/EPCIS/blob/84d89c56dadab374f1da2c7beaeae3911ed79015/JSON-Schema/EPCIS-Event-JSON-Schema.json

**Comment by OR13** [comment]
Link is broken.

**Comment by OR13** [comment]
Make a recommendation on what action should be taken.

**Comment by nissimsan** [comment]
[This](https://github.com/w3c-ccg/traceability-vocab/issues/385#issuecomment-1227045288) explains the broken link.

**Comment by nissimsan** [comment]
After chatting with @mgh128 and @CraigRe yesterday, I suggest that we just pursue with a direct implementation of the EPCIS events, as is intended with issue https://github.com/w3c-ccg/traceability-vocab/issues/385. 
Closing this.
