### ISSUE TITLE
Please add a form for SC-237A

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-vocab#389]
@rhofvendahl Need a credential for for [SC-237A](https://www.ams.usda.gov/resources/sc237a)

**Comment by OR13** [comment]
Direct link to the form: https://www.ams.usda.gov/sites/default/files/media/SC237A.pdf

**Comment by brownoxford** [comment]
@mprorock or @rhofvendahl please provide more information here.

**Comment by OR13** [comment]
Action item to create the necessary certificate type?

**Comment by rhofvendahl** [comment]
PR implementing this [here](https://github.com/w3c-ccg/traceability-vocab/pull/608)

@mprorock did you mean to create a credential for SC-237A in addition to a `common` schema?
