### ISSUE TITLE
Need some specific GAP VCs

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-vocab#390]
@rhofvendahl 
Need credentials for the following: 

[Harmonized GAP Checklist](https://www.ams.usda.gov/sites/default/files/media/HarmonizedGAPsChecklist5.pdf)
[Harmonized GAP Plus Checklist](https://www.ams.usda.gov/sites/default/files/media/HarmonizedGAPsPlusChecklist3.pdf)

and related:
[Food Defense System Survey](https://www.ams.usda.gov/sites/default/files/media/Food%20Defense%20System%20Survey.pdf)
[PSA Audit](https://www.ams.usda.gov/sites/default/files/media/Sample_Audit_Report%5B1%5D.pdf)

You will want to extend ag inspection and add specific fields as needed - there may be an opportunity to have a "gap certificate" that then just has a form name in there to specify the various details on the forms 

n.b. a Version field will be critical on the gap forms - e.g. normal gap is on v5, plus is on v3

**Comment by rhofvendahl** [comment]
@OR13 Thanks, I'll get on this

**Comment by mprorock** [comment]
@rhofvendahl let's also add an explicit organic certification and organic inspection/checklist - see [here](https://www.ams.usda.gov/services/organic-certification) for a good starting place
