### ISSUE TITLE
Follow up on qudt

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#393]
https://github.com/OR13/OR13/issues/1
https://github.com/qudt/qudt-public-repo/issues/247

cc @nissimsan can you take this one over?

**Comment by brownoxford** [comment]
Discussed on call, @nissimsan will re-ping on this one.

**Comment by nissimsan** [comment]
I looked into this. QUDT does not have a role to play here; QUDT is focused on units, not which type of measurement is conducted. 

I suggest we close this ticket and continue our search for a proper metallurgy tests vocabulary on a fresh issue which isn't premised on QUDT.
