### ISSUE TITLE
Build context as a github/npm package

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#399]
we should bundle the traceability context into an easy-to-use NPM package so that organizations can reference that package rather than dynamically fetching the context.

This allows companies to use the same package, and to use normal semantic versioning to protect different environments.

**Comment by OR13** [comment]
see examples:

https://github.com/transmute-industries/verifiable-data/tree/main/packages/did-context
https://github.com/transmute-industries/verifiable-data/tree/main/packages/credentials-context

**Comment by OR13** [comment]
I would suggest we not attempt this until we plan to publish the vocabulary in a more formal (permanent) way.

**Comment by BenjaminMoe** [comment]
The code to generate the context from the schema's is defined here: https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/scripts/openapi-to-context.js#L19.

I"m not sure that this is something that would be widely applicable to NPM. We have a specific use case for taking a list of schemas and converting them into `@context`. I'm not sure how widely applicable that would be to other projects. I think that people can copy and paste and adapt the code as needed, and maybe an generic approach will emerge from there.

**Comment by BenjaminMoe** [comment]
Suggestion. Close and we can create a new issue once we have a static version.
