### ISSUE TITLE
`Certificate` postfix presents a barrier to adoption

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#416]
Look, I get there a technical convention we're aligning to. But the main audience for our schemas is business folks which neither should, nor do, care about such conventions. They rather seem confused about it, and I find myself explaining "that's just a technical naming convention" every single time I introduce the trace-vocab. 

If I can convince the rest of you, there's a secondary issue about name clashing with many of the schemas used in the corresponding credentialSubject. 

But business people we have interviewed have consistently found our naming convention confusing, and I'm looking for a way to address it?

**Comment by BenjaminMoe** [comment]
There's a pragmatic aspect that isn't being addressed by this. The reason for the `Certificate` postfix is to differentiate from the `credentialSubject`. We have a `BillofLading` JSON object representation, and then we have a `BillofLadingCertificate` which is a Verifiable Credential with an issuer and a proof around a `BillOfLading`. With respect to JSON-LD and the RDF representation we can't use the same name for both the Verifiable Credential and the `credentialSubject`. 

This issue is too broad and does not propose a solution for what the approach should be.

**Comment by OR13** [comment]
- https://json-ld.org/spec/latest/json-ld/#specifying-the-type
- https://www.w3.org/TR/vc-data-model/#types

`credentialSubject.type` -> the type, or class of a subject.

`vc.type` -> the type or class of a verifiable credential, certificate, signed document.

If we follow a convention for defining types of certificates, I would expect to see some repetition, either `Credential` or `Certificate`.

**Comment by nissimsan** [comment]
@BenjaminMoe, I'm explicitly calling out that there are practical naming consideration and try to avoid jumping straight to solutioning. The "issue is not too broad" if we avoid bloating it up. 
All I'm saying is: "xxxCertificate" isn't working for me. Is anyone else having problems explaining this? 

Also: I'm not advocating against sticking to a strong naming convention. But our _current_ naming  xxxCertificate convention is no bueno. 

> Certificate postfix is a way to show that a JSON-LD document has an issuer (party it can be traced back to) and a proof (has not been edited and authentic).
But those definitions of `issuer` and `proof` are defined by `VerifiableCredential`, not "Certificate". 

... and on the same point: 
> If we follow a convention for defining types of certificates, I would expect to see some repetition, either `Credential` or `Certificate`.
Postfixing with `Credential` would be easier to explain, I think. It's a much more logical a postfix to a VerifiableCredential - same word. 

Searching vc-data-model, the word "Certificate" is mentioned (five times). But just because a VC can be a Marriage Certificate (or CertificateOfOrigin!), is not a reason to prefix everything with that label.

**Comment by nissimsan** [comment]
Noticing now, the example presentation also has two proofs.

**Comment by nissimsan** [comment]
I suggest we address this problem pragmatically: Replace the word `Certificate` with `Credential`. 
Based on the feedback we are (still) getting on this issue, people are primarily confused about what a "certificate" even is. Whereas they understand that we are making verifiable credentials - that is why you come to trace vocab. 

Also, it would make our type look rather logical. Example: 
```
  "type": [
    "VerifiableCredential",
    "BillOfLadingCredential"
  ]
```
This reads: 
- This is a credential
- It is Verifiable 
- And it's a BillOfLading

**Comment by nissimsan** [comment]
We are getting positive feedback from business/industry on the above suggestion. Marking this ready for PR.

**Comment by BenjaminMoe** [comment]
Put a `Merge First` tag when we address this.

**Comment by brownoxford** [comment]
This was done
