### ISSUE TITLE
Implement a link builder plugin for address to google maps

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#423]
Allow for easily getting GPS coordinate from examples

**Comment by OR13** [comment]
yes, thats part of why I wanted to write this, and easy way to sanity test the fake addresses we are using.

**Comment by OR13** [comment]
I suggest closing this.

**Comment by mkhraisha** [comment]
I believe we should have our fake data is useful to help understand the structure, rather than to use as an example data that is ingested.

@TallTed suggested if that is the case make the data more explicitly fake like "example street"
