### ISSUE TITLE
Representation of a legal entity in traceability vocab

### ISSUE THREAD

**Issue by Therecanbeonlyone1969** [w3c-ccg/traceability-vocab#44]
We need to be able to define and later on identify a legal entity within the traceability schema to be able to ensure that certain VCs are only issued by legal entities.

Key questions to answer:

- How do we represent an entity (within a supply chain for example)?

- How can we represent a legal entity vs just an entity? Can they be connected?

- How do we distinguish between different government/legal definitions of a legal entity within the traceability vocab?

For Reference & Further Discussion:

From Schema.org:

Legal entity identifier -> see also links to GLEIF in this link
[https://schema.org/leiCode](url) 

Definition of organization from schema.org:
[https://schema.org/Organization](url)

GLEIF LEI framework:
[https://www.gleif.org/en/about-lei/introducing-the-legal-entity-identifier-lei#](url)

IS) 17442 -- Legal Entity in Financial Services:
Part 1:
[https://www.iso.org/standard/78829.html](url)

Part 2:
[https://www.iso.org/standard/79917.html](url)

**Comment by Therecanbeonlyone1969** [comment]
@cstoecker @bumblefudge

**Comment by mprorock** [comment]
these appear to have at least partially been added, however #57 is related as some of these items are missing test vectors and may have to be backed out for a bit

**Comment by mprorock** [comment]
@cstoecker these appear to now be well covered at least for a v1 via pr #71 and related.  anything else you would like to add in the next week or so to address this issue, or am I free to close it out?

**Comment by Therecanbeonlyone1969** [comment]
can close.
