### ISSUE TITLE
Make all type array of string(s)

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#445]
Allowing for the option of string versus array at the top of each schema introduces a huge block of syntax that is not well understood for functionality that is not really needed. Should we drop strings from type in favor of using only arrays for simplicity?

**Comment by TallTed** [comment]
maybe retitle "Make all `type` `array` of `string`(s)"

**Comment by mkhraisha** [comment]
@nissimsan states I believe we have updated this for steel and e-commerce.

@mkhraisha we will need to do this for Crude oil and gas

@mprorock  is this something you would like to do for ag?
