### ISSUE TITLE
Update Traceable Presentation Example

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#455]
https://w3c-ccg.github.io/traceability-vocab/#TraceablePresentation

^ include an example, where the holder is an object or type organization with an address.

**Comment by nissimsan** [comment]
Noticing now, the example presentation also has two proofs.

**Comment by BenjaminMoe** [comment]
I think this was addressed by: https://github.com/w3c-ccg/traceability-vocab/pull/458. @OR13 can we close?
