### ISSUE TITLE
121 of 152 of our examples fail schema validation

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#460]
There is a test for making sure the examples provided in each schema pass schema validation in located here: https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/traceability-schemas/__tests__/schemas-sanity.test.js#L36.

Running it shows that 121 out of 152 schemas do not pass schema validation. 

1. Each one of these needs to be addressed such that the example passes schema validation
2. Schema validation check needs to be added to CI
The whole list is provided below.

    - [ ] AgActivity
    - [ ] AgInspectionReport
    - [ ] AgPackage
    - [ ] AgParcelDelivery
    - [ ] AgProduct
    - [ ] BillOfLading
    - [ ] BindingDataRegistrationCredential
    - [ ] CargoItem
    - [ ] CargoLineItem
    - [ ] ChargeDeclaration
    - [ ] ChemicalProperty
    - [ ] CommissionEvent
    - [ ] ConsignmentItem
    - [ ] ConsignmentRatingDetail
    - [ ] ContactPoint
    - [ ] CrudeOilProduct
    - [ ] Customer
    - [ ] DCSAShippingInstruction
    - [ ] DCSATransportDocument
    - [ ] EntrySummary
    - [ ] EntrySummaryLineItem
    - [ ] Event
    - [ ] FoodGradeInspection
    - [ ] FoodGradeInspectionLot
    - [ ] FoodGradeInspectionSample
    - [ ] FreightManifest
    - [ ] GeoCoordinates
    - [ ] HouseBillOfLading
    - [ ] IATAAirWaybill
    - [ ] ImmediateDelivery
    - [ ] ImmediateDeliveryEntity
    - [ ] ImmediateDeliveryLineItem
    - [ ] ImporterSecurityFiling
    - [ ] Inbond
    - [ ] InspectionReport
    - [ ] Inspector
    - [ ] Instructions
    - [ ] IntentToSell
    - [ ] Invoice
    - [ ] InvoiceRegistrationEvidenceDocument
    - [ ] IssuerAgent
    - [ ] LEIauthority
    - [ ] LEIentity
    - [ ] LEIevidenceDocument
    - [ ] LEIregistration
    - [ ] LegalEntityIdentifierCredential
    - [ ] LinkRole
    - [ ] MasterBillOfLading
    - [ ] MeasuredProperty
    - [ ] MultiModalBillOfLading
    - [ ] NaturalGasProduct
    - [ ] OGBillOfLading
    - [ ] Observation
    - [ ] OrderRegistrationEvidenceDocument
    - [ ] OrderedItem
    - [ ] Organization
    - [ ] PGAStatusMessage
    - [ ] Package
    - [ ] PackingList
    - [ ] ParcelDelivery
    - [ ] PartOfOrder
    - [ ] Person
    - [ ] Phytosanitary
    - [ ] Place
    - [ ] PostalAddress
    - [ ] Product
    - [ ] ProductRegistrationEvidenceDocument
    - [ ] PurchaseOrder
    - [ ] Qualification
    - [ ] QuantitativeValue
    - [ ] SIMASteelImportLicense
    - [ ] SIMASteelImportProductSpecifier
    - [ ] SeaCargoManifest
    - [ ] Seal
    - [ ] ServiceCharge
    - [ ] ShippingInstructions
    - [ ] ShippingStop
    - [ ] SoftwareBillOfMaterials
    - [ ] SteelProduct
    - [ ] Template
    - [ ] TraceabilityAPI
    - [ ] TradeLineItem
    - [ ] TransferEvent
    - [ ] TransformEvent
    - [ ] Transport
    - [ ] TransportDocument
    - [ ] TransportEquipment
    - [ ] TransportEvent
    - [ ] USMCACertifier
    - [ ] UsdaSc6
    - [ ] WayBillRegistrationCredential
    - [ ] Workflow
    - [ ] ppq587
    - [ ] BillOfLadingCertificate
    - [ ] CTPATCertificate
    - [ ] CertificateOfOrigin
    - [ ] CommercialInvoiceCertificate
    - [ ] CrudeOilProductCertificate
    - [ ] DCSAShippingInstructionCertificate
    - [ ] DCSATransportDocumentCertificate
    - [ ] EntrySummaryCertificate
    - [ ] FoodGradeInspectionCertificate
    - [ ] FreightManifestCertificate
    - [ ] HouseBillOfLadingCertificate
    - [ ] IATAAirWaybillCertificate
    - [ ] ImmediateDeliveryCertificate
    - [ ] ImporterSecurityFilingCertificate
    - [ ] MasterBillOfLadingCertificate
    - [ ] MultiModalBillOfLadingCertificate
    - [ ] NaturalGasProductCertificate
    - [ ] PGAStatusMessageCertificate
    - [ ] PackingListCertificate
    - [ ] ProformaInvoiceCertificate
    - [ ] PurchaseOrderCertificate
    - [ ] SIMASteelImportLicenseApplicationCertificate
    - [ ] SIMASteelImportLicenseCertificate
    - [ ] SeaCargoManifestCertificate
    - [ ] ShippingInstructionsCertificate
    - [ ] SoftwareBillofMaterialsCertificate
    - [ ] USMCACertificateOfOrigin
    - [ ] VerifiableBusinessCard

**Comment by TallTed** [comment]
Typo in title makes it confusing -- "121 or 153" should be "121 of 153"...

**Comment by nissimsan** [comment]
We did this.
