### ISSUE TITLE
Representing Raw Materials

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#461]
In the context of steel and other metals, the smelting manufacturing process can be a function of either raw ore or scrap metal

We propose to define the raw material inputs in greater detail (example):

```json
[
  {
    "name": "Iron Ore (Goethite)",
    "inchiKey": "AEIXRCIKZIZYPM-UHFFFAOYSA-M"
  },
  {
    "name": "Aluminum Ore (Bauxite)",
    "inchiKey": "XXHQVTGCFGYKNL-UHFFFAOYSA-N"
  },
  {
    "name": "Cobalt Ore (Cobaltite)",
    "inchiKey": "SAXCKUIOAKKRAS-UHFFFAOYSA-M"
  },
  {
    "name": "Scrap Metal (Iron)",
    "inchiKey": "AEIXRCIKZIZYPM-UHFFFAOYSA-M"
  }
]
```

**Comment by mkhraisha** [comment]
Are you proposing adding a "raw material" vocabulary term with a generic structure or creating each of these as a schema?

+1 to the first if so.

**Comment by OR13** [comment]
We need reference certificates related to mineral extracted from specific locations.

**Comment by nissimsan** [comment]
We need help providing example certificates which we can model from.

**Comment by mkhraisha** [comment]
I believe the current sentiment is that we are moving away from generic vocab terms like this. Plesae close if you agree @OR13
