### ISSUE TITLE
Update instructions for publishing minutes

### ISSUE THREAD

**Issue by BenjaminMoe** [w3c-ccg/traceability-vocab#464]
@mkhraisha added how to publish the meeting minutes with https://github.com/w3c-ccg/traceability-vocab/pull/456. This issue describes any misunderstanding or gaps that need to be added into the documentation, such that anyone running the call will be able to execute the instructions to publish the minutes.

1. Do we need to stop recording first?
2. Add a link to the meetings repo (https://github.com/w3c-ccg/meetings)
3. How do we address the transcriber failing? (might need to be a separate issue)
4. Do we need to update https://github.com/w3c-ccg/meetings/blob/main/scribe-tool/people.json?

**Comment by BenjaminMoe** [comment]
1. We need to boot everyone out of the meeting when done
2. Done in Chris' interop readme
3. Use the menu to stop and start transcriber without stopping and starting the meeting
4. No. 

@OR13 suggests not using auto-scribe. https://www.w3.org/2008/04/scribe.html

**Comment by brownoxford** [comment]
Ready for PR once trace-interop has been updated to include instructions for scribes

**Comment by brownoxford** [comment]
This was done
