### ISSUE TITLE
Add "Revocation List 2020" Example to Use Cases

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#47]
https://github.com/w3c-ccg/traceability-vocab/pull/45#pullrequestreview-538674505

https://github.com/w3c-ccg/vc-status-list-2021

**Comment by OR13** [comment]
@mprorock @mkhraisha @bumblefudge what kind of credentials would it be best to show revocation on?

Seems like Licenses would be a good target.

**Comment by msporny** [comment]
2020 is outdated, please target Status List 2021.

**Comment by mkhraisha** [comment]
Licences seems like a very important one, however theres a few things that we may need to discuss:

How are we tackling corrections? im assuming its revoke the old credential and issue a new one, in which case most things that would undergo corrections ( inspection reports, declarations etc) might be really good candidates to show revocations.

**Comment by mprorock** [comment]
We revoke and issue new with corrected data for ag inspection stuff to match customer needs and current paper work flows

**Comment by OR13** [comment]
We are seeking example of credential that really ought to be revocable.

If we can't find any for Steel, ECommerce, Oil and Gas, or Ag, we should close this.

**Comment by mprorock** [comment]
can we address this by adding to the generators so that it is handled correctly and consistently for all credential examples we generate?

**Comment by OR13** [comment]
Decision to add an example of "Revocation List 2020".

**Comment by TallTed** [comment]
Discussed in 2021-08-17 call --
1. Example of "Revocation List 2020" will be added now, per prior RESOLUTION.
2. Example of "Status List 2021" (or later) will replace the above when "Status List 2021" (or later) is adopted by the VC HTTP API (or whatever new name)

**Comment by mprorock** [comment]
PROPOSAL: we should note in the spec that: we recommend the use of credential status in all credentials, and for purposes of complete examples of VCs we are including credential status in all examples

**Comment by OR13** [comment]
We need a real use case.

**Comment by OR13** [comment]
I suggest we handle on specific credentials, that require it.

**Comment by mprorock** [comment]
Closing issue per discussion on call.  VCs that should have revocation should be noted as such by the example authors
