### ISSUE TITLE
Use Case: Energy / Power Traceability 

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#516]
Here is a high-level overview of the authentication mechanism and tracking used today for OASIS, inter-tie electricity scheduling.

Everything starts with the [NAESB registry EIR.

- https://www.naesb.org/pdf4/webregistry_mo_registration_quick_ref_guide_v1.0_0417.pdf

Entities involved in inter-tie electricity transactions must register with NAESB’s EIR, see link above.

The registration process requires a party to obtain a NAESB compliant X.509 certificate from an accredited certificate authority (ACA); 

- https://www.naesb.org/pdf4/ac_authorities_2022.pdf

Entities use their digital certificates for identification in OASIS; 

- https://www.naesbwry.oati.com/NAESBWRY/sys-index.wml

Inter-tie transactions are scheduled and tracked, using an E-TAG; 

- https://en.wikipedia.org/wiki/NERC_Tag

E-TAG’s are used to “connect the dots” and settle transactions that flow across Balancing Authorities.

Credit to Dick Brooks for sharing this information with me.

**Comment by VladimirAlexiev** [comment]
In Europe (but also many other countries) it all starts with [Energy Identification Code (P8645)](https://www.wikidata.org/wiki/Property:P8645).
It's used for Electricity and Gas, and is given to parties, network operators, energy markets and exchanges, infrastructure like gas and power lines, power plants and generators.

- WD has only 3k EIC but lists a bunch of local lists that have more.
- For electricity, ENTSOE keeps a central register: https://www.entsoe.eu/data/energy-identification-codes-eic/eic-approved-codes/ , about 50k codes.

**Comment by BenjaminMoe** [comment]
Action item is unclear.

**Comment by OR13** [comment]
Suggest closing, there is no implementer interest at this time.

**Comment by nissimsan** [comment]
Closing, no interest at this time.
