### ISSUE TITLE
traceability-vocab and traceability-interop README files should be synced 

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/traceability-vocab#526]
The [README here](https://github.com/w3c-ccg/traceability-vocab) is much shorter and, I believe, is far out of date.

The [README there](https://github.com/w3c-ccg/traceability-interop) is much longer and, I believe, is much more current (though not quite finished -- some links should be added to, e.g., the Standing Agenda portion, for, e.g., the default sort order to be used for Issue review, i.e., [`https://github.com/w3c-ccg/traceability-vocab/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc`](https://github.com/w3c-ccg/traceability-vocab/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc))

**Comment by nissimsan** [comment]
Needs a diff and intelligent choice of what to bring over. 
Interop has been polished, vocab needs updating.
