### ISSUE TITLE
usage of IDs and Types in schemas

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/traceability-vocab#53]
This question is more for clarification than anything else, but I wanted to make sure I was clear before getting too far...
In most of the existing schemas, the properties will be defined this way:
```
"identifier": {
      "$comment": "{\"term\": \"identifier\", \"@id\": \"https://schema.org/identifier\"}",
      "title": "Property Identifier",
      "description": "Identifiers for a property.",
      "type": "string"
},
```
The @id references the schema entry for GeoCoordinates and it's basically exactly what's defined in schema.org.  
As I'm building out larger schemas, there might be multiple identifiers (for example) in the same schema.  This will of course cause issues because you can't have two identical @id's in the same schema.  Also, given there are two identifier types in the same schema there is some sort of differentiation there that should be captured. 
This problem is especially relevant in having multiple places in the same schema (post of entry vs. foreign port export, for example)
All that to say, what I've done in an upcoming PR is to have the IDs reference the schema they're in and use @type to point to the schema type.  Like this (in a ppq203.json schema):
```
"certificateNumber": {
            "$comment": "{\"term\": \"certificateNumber\", \"@id\": \"https://w3id.org/traceability/schemas/ppq203.json#certificateNumber\", \"@type\": \"https://schema.org/identifier\"}",

...

},
        "carrierId": {
            "$comment": "{\"term\": \"carrierId\", \"@id\": \"https://w3id.org/traceability/schemas/ppq203.json#carrierId\", \"@type\": \"https://schema.org/identifier\"}",

...

},
```

Does this make sense as a proper way to define properties moving forward that are of a certain type but have a more specific definition in the schema?
@OR13 @mprorock @mkhraisha

**Comment by OR13** [comment]
side note, you must space `@` in github to avoid pinging users who squat on obvious names like `@type` :)

This is a great question, and I don't have a great answer, but I will try and also ping @dlongley @msporny @tplooker 

```
@id
Used to uniquely identify things that are being described in the document with IRIs or blank node identifiers. This keyword is described in § 3.3 Node Identifiers.
...
@type
Used to set the data type of a node or typed value. This keyword is described in § 4.5 Typed Values.
```
id -> https://json-ld.org/spec/latest/json-ld/#node-identifiers
type -> https://json-ld.org/spec/latest/json-ld/#typed-values

`"@id": "https://w3id.org/traceability/schemas/ppq203.json#carrierId"` -> this looks wrong to me.

these values become what you are signing over, and semantically, the intention is to sign over the information, not its representation is a specific schema....

hence:

```
"inchi": {
          "@id": "http://purl.obolibrary.org/obo/chebi/inchi"
        },
```

although this is an academic ontology that fails to define its terms properly with human readable links. That URL should take you to a web page which describes what "inchi" is... for example: https://en.wikipedia.org/wiki/International_Chemical_Identifier

I suppose taking you to a JSON Schema is about 100000% times better than taking you to nothing.... 

I am not sure how to improve our documentation around when to use `@id` and when to use `@type` beyond pulling the parts of the JSON-LD spec i mentioned above...

**Comment by brianwmunz** [comment]
The reason this has even come up is because the test suite will fail due to a lack of context (because identical IDs causes issues).  So I guess another way to frame this would be that you have an ID for carrier and one for a certificate.  Technically, each one should have its ID point to some vocab somewhere that describes it?  If there were multiple of carriers, etc. we would just make it an array I suppose.  I guess a question would be: what if there isn't anything in schema.org, gs1 or the normal cast of characters that describes exactly what we're defining?  That's why I pointed to itself, which I realize isn't great.  I guess I could update the help html and point there :)

**Comment by OR13** [comment]
Examples from the vc data model:

https://github.com/w3c/vc-data-model/blob/master/contexts/credentials/v1#L23

https://github.com/w3c/vc-data-model/blob/master/contexts/credentials/v1#L68

https://github.com/w3c/vc-data-model/blob/master/contexts/credentials/v1#L86

**Comment by OR13** [comment]
Related https://github.com/w3c-ccg/traceability-vocab/pull/51/files#r542694993

**Comment by brianwmunz** [comment]
Closing this issue because Orie did a good job describing how this should be navigated I think.
