### ISSUE TITLE
namespace problems

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#531]
I took the ttl from https://github.com/w3c-ccg/traceability-vocab/issues/395#issuecomment-1110300096, added prefixes, and run it through `riot --formatted ttl` to see it in a better way.

I noticed the following prefix problems:

- this is a terrible namespace. Please make up one that starts from dcsa.org:
```
@prefix dcsa:     <https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.1#/components/schemas/> .
```
- You use `https` but the actual schema ontology semantic URLs use `http`:
```
@prefix schema1:  <https://schema.org/> .
```
- You use two namespaces for `traceability`: with and without slash
```
@prefix trace:    <https://w3id.org/traceability/#> .
@prefix trace1:   <https://w3id.org/traceability#> .
```

- previously reported to @nissimsan : use slash, not slash+hash
```
@prefix uncefact: <https://service.unece.org/trade/uncefact/vocabulary/uncefact/#> .
@prefix uncl1153: <https://service.unece.org/trade/uncefact/vocabulary/uncl1153/#> .
```

**Comment by nissimsan** [comment]
Hi @VladimirAlexiev, 

Regarding dcsa, I 100% agree. "Terrible" is an appropriate word. They don't have an actual vocab, this is the best I could come up with, prioritizing something that resolved to a kind of definition. In part, this is meant as an encouragement. 

Regarding uncefact, the /# is getting addressed [here](https://github.com/uncefact/spec-jsonld/issues/25). I don't want to make corrections here before the uncefact vocab is v1.0 baselined.

**Comment by VladimirAlexiev** [comment]
Important takeaway https://github.com/dcsaorg/DCSA-OpenAPI/issues/141: 
JSON API and JSON Schema URLs are not necessarily good semantic URLs.

**Comment by BenjaminMoe** [comment]
@VladimirAlexiev any follow up on this?

**Comment by nissimsan** [comment]
I think this ticket has served its purpose. These suggestions are being tackled individually on the relevant repos, and we also have tickets to follow up (such as https://github.com/w3c-ccg/traceability-vocab/issues/536). 

I suggest we close - no need to keep this ticket around.

**Comment by nissimsan** [comment]
Closing, going with https://github.com/w3c-ccg/traceability-vocab/issues/536

**Comment by OR13** [comment]
Suggest closing based on conversation on call.

**Comment by OR13** [comment]
https://github.com/w3c-ccg/traceability-vocab/search?q=https%3A%2F%2Fw3id.org%2Ftraceability%2F%23

**Comment by nissimsan** [comment]
We do do this: 
https://w3c-ccg.github.io/traceability-vocab/#BillOfLadingCredential
