### ISSUE TITLE
Example data should be either more fake or more real

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#553]
#423  tangentially touched on this point during conversation.

Our data is misleading as it looks like it could be real but it isn't. We should either make it more explicitly fake or make it map to real places.

**Comment by brownoxford** [comment]
@OR13 commented that this was originally more about making sure that data is valid, e.g., not using 999.0 as a latitude value.

**Comment by brownoxford** [comment]
Closing as too general - if invalid example data is found, please open an issue to fix the specific problem.
