### ISSUE TITLE
Rename `TraceablePresentation` to `WorkflowPresentation`

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#555]
Would WorkflowPresentation be clearer than TraceablePresentation? 

```
   "type":[
      "VerifiablePresentation",
      "WorkflowPresentation"  //  <- suggestion
   ],
   "workflow":{
      "instance":[
         "urn:uuid:f5fb6ce4-b0b1-41b8-89b0-331ni58b7ee0"
      ],
      "definition":[
         "urn:uuid:n1552885-cc91-4bb3-91f1-5466a0be084e"
      ]
   },
```

**Comment by TallTed** [comment]
First question seems obvious: Why does `TraceablePresentation` not suffice any longer?

Second is: What does `WorkflowPresentation` do, that `TraceablePresentation` does not?

**Comment by mkhraisha** [comment]
I think it doesn't suffice because this presentation is a presentation that pertains to a workflow, it has workflow ids, and workflow definitions, and doesn't really talk about anything traceable.

I could see this being a better path forward.

**Comment by TallTed** [comment]
That would seem to suggest that `traceability-vocab` and `traceability-interop` may also want renaming, though I'm not sure that `workflow-vocab` and/or `workflow-interop` will be any better...

I'd like a link to the use(s) and definition(s) of `WorkflowPresentation` (or `TraceablePresentation`) in existing document(s), rather than just the snippet above, as I think that this renaming can only be considered with such _in situ_ examination.

**Comment by BenjaminMoe** [comment]
I think that `WorkflowPresentation` is a more direct description of the functionality provided. "This is a presentation that is part of a Workflow".

I think that "Traceable Presentation" is a clearly defined term for the implications. "This presentation represents a series of credentials that can be represented as an RDF graph, to be able to query over to _trace through_ the information".

**Comment by TallTed** [comment]
I guess we're working on `TraceableWorkflowPresentation`s, which is to say, the `Traceable` subset of all `WorkflowPresentation`s (akin to the idea that `VerifiablePresentation`s are the `Verifiable` subset of all `Presentation`s).

Key remaining questions are whether either `WorkflowPresentation` or `TraceablePresentation` is meaningful on its own, and whether `TraceableWorkflowPresentation` is just too unwieldy to be considered further.

Fortunately(?), `WorkflowTraceablePresentation` seems to make little sense on its own, and can probably be discarded.

**Comment by nissimsan** [comment]
https://w3c-ccg.github.io/traceability-vocab/#TraceablePresentation

**Comment by nissimsan** [comment]
General agreement on the call. 

Noting that I also minted the original name TraceablePresentation.

**Comment by nissimsan** [comment]
It's probably too late for this by now.
