### ISSUE TITLE
Test Suite link is broken

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#565]
<img width="783" alt="Screen Shot 2022-09-16 at 12 44 59 PM" src="https://user-images.githubusercontent.com/8295856/190700931-cf1d79fd-71d6-49ea-8a89-e6f0b57afb20.png">

**Comment by mkhraisha** [comment]
The issue here is that the HTML doc has an href to `"/testsuite/"`, the deployment on github pages expects it to be under `traceability-vocab/testsuite`.
serving locally a link to `testsuite` works.
