### ISSUE TITLE
move steel-workflow.png to resources

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#567]
Move docs/steel-workflow.png to docs/resources/docs/steel-workflow.png.
Same for ecommerce-workflow.png
Fix any link in documentation.

**Comment by BenjaminMoe** [comment]
Sounds good.

**Comment by OR13** [comment]
suggest closing this, its been completed

**Comment by nissimsan** [comment]
This has been significantly updated - let's close.
