### ISSUE TITLE
https://w3id.org/identifier

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#570]
Some schemas use https://w3id.org/identifier but such property doesn't exist:
(nor can it, because the pattern at that site is `https://w3id.org/<ontology>/<property>` or deeper
- NaturalGasProduct.yml : 1
- Inbond.yml: 6
- CrudeOilProduct.yml: 1

**Comment by OR13** [comment]
This query returns evidence that this still needs to be corrected:

https://github.com/w3c-ccg/traceability-vocab/search?q=https%3A%2F%2Fw3id.org%2Fidentifier
