### ISSUE TITLE
identifier wrongly used as class

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#572]
This shows wrong uses of `identifier` as a type:
```
grep -r '@type.*identifier' .
```
- common/ppq203.yml: 2
- common/UsdaSc6.yml: 5

https://schema.org/identifier is a property not class. 
#571 shows how to construct a class `:Identifier` to avoid identifier conflation issues.

**Comment by nissimsan** [comment]
@rhofvendahl will you pls look into this?

**Comment by rhofvendahl** [comment]
@VladimirAlexiev Thanks for raising this issue. As mentioned in https://github.com/w3c-ccg/traceability-vocab/issues/569 unless there are objections for now I'd like to simply remove these` '@type`'s.

**Comment by nissimsan** [comment]
We did this.
