### ISSUE TITLE
unLocode, iataAirportCode

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#578]
Place.yml uses these two identifiers, but:
- they are not shown in the example
- it's unclear how they should be used:
   1. applicable only to cities/ports with LOCODE, respectively airports, OR
   2. should designate the closest **place(s)** with LOCODE, respectively IATA code, OR
   3. should designate the single **place** with LOCODE/IATA to be used for delivery to this place, for this particular shipment

By "closest" I mean "logistically closest", which has complications:
- may not be geographically closest, eg the closest IATA code may be an non-commercial or non-cargo airport
- do we mean fastest/shortest/cheapest route from an airport to this place?
- could be multivalued, eg two LOCODE ports might be often used to serve this place

Item iii. would make this Place record local to the shipment, i.e. cannot be reused between shipments.
For these reasons, I think the schema should document option i. 
If someone wants to specify "go through that IATA airport", we need some "routing preferences" object.

**Comment by brownoxford** [comment]
Discussed on call, unclear of action items.

**Comment by VladimirAlexiev** [comment]
@brownoxford The original issue was that the meaning of `unLocode` and `iataAirportCode` isn't clear.
Please clarify in the prop definition whether `i` these are applicable only to places with such codes (eg sea port cities, airports). 
If not, then the much more complicated alternatives `ii` and `iii` come into consideration.

@nissimsan please add `iataAirportCode` to the example, but ensure it and `unLocode` are consistent with the address. When you mix Missouri, Cyprus and Denmark in one example, people are unsure what you mean.

Last but most important, the semantic mappings of these props are wrong:
https://github.com/w3c-ccg/traceability-vocab/blob/c66bdb15cf69189ef282d6c3dd30ee124ecd80d6/docs/openapi/components/schemas/common/Place.yml#L46-L60
- https://vocabulary.uncefact.org/Location is a class, not a data property. 
- https://onerecord.iata.org/cargo/Location#code is obsolete (the page doesn't' show meaningful content) and in any case not an RDF property. Use https://schema.org/iataCode

---

@nissimsan some comments about your other project (if you give me a link, I'll make an issue there)

Unfortunately vocabulary.uncefact.org has not defined its own prop for `unlocode`.
`curl  https://vocabulary.uncefact.org/unlocode# -H Accept:application/ld+json -o unlocode.jsonld`
shows that the prop used is eg `"rdf:value":"ADALV"`: not a good choice.

Adding `curl -v` shows some problems with the HTTPS setup there:
```
* schannel: failed to decrypt data, need more data
{ [98304 bytes data]
```

The command shown at https://vocabulary.uncefact.org/unlocode-about doesn't work on windows.
Please change it to this, which should work on both windows and linux (you can remove `-o` if you don't like it):
```
curl  https://vocabulary.uncefact.org/unlocode# -H Accept:application/ld+json -o unlocode.jsonld
```
