### ISSUE TITLE
Context Errors from schema IDs

### ISSUE THREAD

**Issue by brianwmunz** [w3c-ccg/traceability-vocab#59]
When running the tests on new schemas, there are often confusing errors due to the link that is populated for @id in the $comment on properties.  I realize that this id should simply be a link to a human readable page explaining the property itself.  So, I'm confused why often the link causes the linked data conformance test (linked-data-conformance.test.js) to throw an error.  Here is a simple example.  When I run the test on AgProduct with this code as the property value:
```
        "product": {
            "$comment": "{\"term\": \"product\", \"@id\": \"https://schema.org/Product\"}",
            "title": "Product",
            "description": "Product details as specified in the Product.json schema",
            "$ref": "https://w3id.org/traceability/schemas/Product.json"
        }
```
I get the follow error when running that test: `{ type: 'MISSING_PROPERTIES_IN_CONTEXT', details: '["product"]' }`
However, when I run it with this code pointing to GS1:
```
        "product": {
            "$comment": "{\"term\": \"product\", \"@id\": \"https://www.gs1.org/voc/Product\"}",
            "title": "Product",
            "description": "Product details as specified in the Product.json schema",
            "$ref": "https://w3id.org/traceability/schemas/Product.json"
        }
```
the tests pass.
I'm confused as to why this is, partially because of this specific case of schema vs. gs1, but mostly because I'm wondering why the test is strict on ID which is something that I thought was meant to be mostly for humans and not machine readable.
Thanks.

**Comment by mprorock** [comment]
closing this out as there is any easy fix via addition of a version parameter to the `@id` for items that share a common type as specified by id but have a differing term - see pr #69 for example in the intent to sell object
