### ISSUE TITLE
Metallurgy test vocabulary

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#594]
We need identifiers for mechanical properties tests. According to https://en.wikipedia.org/wiki/Tensile_testing#Standards it seems like the relevant standards include: 
- `https://www.iso.org/obp/ui/#iso:std:iso:6892:-1:ed-3:v1:en`
- `https://www.astm.org/e0008_e0008m-22.html`
- `https://webstore.ansi.org/Standards/JIS/jis22412011`

All standards are of the "you must buy this PDF document" type. 

This is continuing from https://github.com/qudt/qudt-public-repo/issues/247, searching for suitable metallurgy test vocabulary.

**Comment by nissimsan** [comment]
ISO can be used to express rather okay looking LD from publicly available vocab/documentation. 

Here's an example from [Mill Test schema](https://w3c-ccg.github.io/traceability-vocab/#MillTestReportCertificate) updated with ISO identifiers:

```
          {
              "type": [
                "MechanicalProperty"
              ],
              "identifier": "https://www.iso.org/obp/ui/#iso:std:iso:6892:-1:ed-3:v1:en:term:3.3",
              "name": "Percentage elongation",
              "description": "[elongation (3.3)](https://www.iso.org/obp/ui/#iso:std:iso:6892:-1:ed-3:v1:en:term:3.3) expressed as a percentage of the [original gauge length (3.1.1)](https://www.iso.org/obp/ui/#iso:std:iso:6892:-1:ed-3:v1:en:term:3.1.1)"
          },
```

**Comment by brownoxford** [comment]
Discussed on call, need more info from @nissimsan

**Comment by mkhraisha** [comment]
Percentage elongation should go to https://www.iso.org/obp/ui/#iso:std:iso:6892:-1:ed-3:v1:en:term:3.4

**Comment by mkhraisha** [comment]
closing as changes are not requested by industry, if it comes up again happy to revisit
