### ISSUE TITLE
Fix GeoCoordinates

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#633]
This is an example of an invalid GeoCoordinate (specifically `long -100`) - there are a few more such examples. Let's get them fix into real GeoCoordinates. 

```
        "geo": {
          "type": ["GeoCoordinates"],
          "latitude": "25.682338876065607",
          "longitude": "-100.31373788104028"
        },
```

**Comment by nissimsan** [comment]
And while we're at it, when changing, let's pick some coordinates in the vicinity/same country of the Location postalAddress.

**Comment by nissimsan** [comment]
Seemed okay as it was. 

Can't find any other illegal lat/longs either. Weird ones, sure, but all somewhere on planet Earth. 

Let's close this.

**Comment by TallTed** [comment]
`long -100` is indeed valid. Longitude ranges from –180° to +180°.

For completeness, Latitude ranges from –90° to +90°.
