### ISSUE TITLE
Traceability-vocab is not a "vocab"

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#635]
While sometimes we are forced to invent our own terms, it is our [stated mission striving not to](https://w3id.org/traceability/#vocabulary-linkage). So the name "traceability-_vocab_" actually seems misleading. We are sending a signal that "this is yet another vocab", which is the opposite of our intention. 

Is a name correction even practically possible at this stage? What is the appetite of an alternative name like "tracability-schemas"?

**Comment by OR13** [comment]
I suggest not changing the name, until the work progresses to a more formal location.
