### ISSUE TITLE
Lets add a section on GS1

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#700]
With some introductory text, and a direct link to https://ref.gs1.org/gs1/vc/

We might also want to add GS1 as a participant, and have their credentials listed, under credentials of interest.

**Comment by paulfdietrich** [comment]
I can take this

**Comment by BenjaminMoe** [comment]
@paulfdietrich any updates?

**Comment by mkhraisha** [comment]
@paulfdietrich are you still interested in adding this in? 

if so we'll need it soon for v1.0

**Comment by mkhraisha** [comment]
Putting a pending-close label on this, if this is not updated within the next 2 weeks, we will close this issue.
