### ISSUE TITLE
Reflect UUID requirements from trace-interop 

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#702]
Our specs have drifted...

https://w3c-ccg.github.io/traceability-vocab/#verifiable-credential
and 
https://w3c-ccg.github.io/traceability-vocab/#verifiable-presentation

must be synched with the 

https://w3c-ccg.github.io/traceability-interop/draft/#presentations
and 
https://w3c-ccg.github.io/traceability-interop/draft/#credentials

Accordingly, our credential examples must be updated to only use UUIDs.

**Comment by nissimsan** [comment]
Looking for volunteers on this

**Comment by nissimsan** [comment]
GS1 credentials might have resolving ids. We need to be able to fit that in.

**Comment by BenjaminMoe** [comment]
For clarification, what is the ask here? To have a specific regex for the expected id format? Or are we okay with a more ambiguous, "as long as it's a valid urn"?

**Comment by nissimsan** [comment]
@mkhraisha , any updates on this?

**Comment by mkhraisha** [comment]
https://w3c-ccg.github.io/traceability-interop/draft/#credentials 

 Remove the as per VC data model, and the quotes and keep the text.

Kill the paragraph In the case of credentials used in systems implementing this specification, a credential ID MUST be a UUID v4 per [[rfc4122](https://w3c-ccg.github.io/traceability-interop/draft/#bib-rfc4122)]. The issuing system MUST return the credential in question with an HTTP request to their API of GET /credentials/{credential-id}
