### ISSUE TITLE
Internationaliz/sation of GS1 credentials

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#705]
In implementing the GS1 credential schemas, the British english spelling clashes with W3C's requirement of American english spelling. Primarily called out on https://github.com/w3c-ccg/traceability-vocab/pull/704. Agreed direction is to accept British english for now, @paulfdietrich will follow up with GS1 and get the spec updated at which point we can come back and correct this. 

Paul, would you mind assigning yourself on this issue?

**Comment by OR13** [comment]
@paulfdietrich

**Comment by paulfdietrich** [comment]
We have agreed to review this and use US English spelling for vocabulary items.  We'll check the doc and ensure there aren't any other gotchas like Authorisation.

**Comment by paulfdietrich** [comment]
This language change was updated in GS1 credentials.  You can find the new context and data model here 

https://ref.gs1.org/gs1/vc/
