### ISSUE TITLE
Include StatusList2021 Context to traceability context?

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#711]
Should we include recommended contexts that are relevant for trace interop in the traceability context such as StatusList2021 or similar?

This would behave similarly to how the 2018 credentials context includes the `ed255192018` context, enabling developers easier "on-ramping" to use the traceability context.

**Comment by OR13** [comment]
IMO, we should close this, v2 bundles these terms.

**Comment by mkhraisha** [comment]
closing as addressed
