### ISSUE TITLE
Tracking IATA IRI bug

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#717]
There's just an in consistency with how the IATA OneRecord ontology is published. 

The IATA ontology explicitly calls that out what their IRIs are, for example `https://onerecord.iata.org/Carrier#airlineCode`:

![image](https://user-images.githubusercontent.com/34443212/227150487-12ed223c-41b0-45b7-94dd-71e95bf73701.png)

However, `https://onerecord.iata.org/Carrier#airlineCode` but this doesn't resolve, whereas `https://onerecord.iata.org#Carrier#airlineCode` does resolve. 

I've raised this inconsistency on the IATA github: https://github.com/IATA-Cargo/ONE-Record/issues/149. This issue is to track how this progresses on IATA's side. 

We are going with the explicitly mentioned IRI. I'm open to arguments for switching to the double-# URIs instead. But I feel pretty confident about sticking with my earlier choice:

- The IATA spec explicitly says the IRI is https://onerecord.iata.org/Carrier#airlineCode
- Double-# URIs are not illegal, but discouraged (second # must be interpreted as a literal), further indicating that's the bug and not IATA's actual intention.

**Comment by nissimsan** [comment]
@mkhraisha, this is a tracking issue, as you requested. 

Personally I don't think it is necessary to track this. The IRIs are explicitly listed. It's annoying that they don't resolve. But I feel confident that when/if the bug gets solved by IATA, they will go with `https://onerecord.iata.org/Carrier#airlineCode` which we are using.

**Comment by nissimsan** [comment]
@nissimsan to make sure this is captured on the IATA repo.

**Comment by nissimsan** [comment]
It's captured alright. I don't know why the link didn't show up on this issue. Here it is: 

https://github.com/IATA-Cargo/ONE-Record/issues/149

I suggest we close this and leave this with IATA.

**Comment by TallTed** [comment]
When you dereference `https://onerecord.iata.org/Carrier#airlineCode`, the client asks the server for `https://onerecord.iata.org/Carrier`, which apparently doesn't exist; in whatever it gets back, the client looks for `id=airlineCode` or `id=https://onerecord.iata.org/Carrier#airlineCode`. 

When you dereference `https://onerecord.iata.org#Carrier#airlineCode`, the client asks the server for `https://onerecord.iata.org`, which does exist; in whatever it gets back, the client looks for `id=Carrier#airlineCode` or `id=airlineCode` or `https://onerecord.iata.org#Carrier#airlineCode`.

If someone has an IATA contact or a way to update their bug, it might be worth adding the above.
