### ISSUE TITLE
Consider improving introduction

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#719]
I like the framing from https://datatracker.ietf.org/doc/draft-ietf-rats-ar4si/

**Comment by OR13** [comment]
Suggest we improve our introductory text, similar to:

   The first paragraph of the May 2021 US Presidential Executive Order
   on Improving the Nation's Cybersecurity [US-Executive-Order] ends
   with the statement "the trust we place in our digital infrastructure
   should be proportional to how trustworthy and transparent that
   infrastructure is."  Later this order explores aspects of
   trustworthiness such as an auditable trust relationship, which it
   defines as an "agreed-upon relationship between two or more system
   elements that is governed by criteria for secure interaction,
   behavior, and outcomes."

   The Remote ATtestation procedureS (RATS) architecture
   [I-D.ietf-rats-architecture] provides a useful context for
   programmatically establishing and maintaining such auditable trust
   relationships.  Specifically, the architecture defines conceptual
   messages conveyed between architectural subsystems to support
   trustworthiness appraisal.  The RATS conceptual message used to
   convey evidence of trustworthiness is the Attestation Results.  The
   Attestation Results includes Verifier generated appraisals of an
   Attester including such information as the identity of the Attester,
   the security mechanisms employed on this Attester, and the Attester's
   current state of trustworthiness.

**Comment by nissimsan** [comment]
Good motivation based on policy. Good inspiration, even if we might need to keep a more international focus.

**Comment by nissimsan** [comment]
Supply chain transparency; US and EU policy
