### ISSUE TITLE
Remove unLocode from DeliverySchedule

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#733]
We should remove unLocode from the example: https://github.com/w3c-ccg/traceability-vocab/pull/721#discussion_r1157578082

**Comment by mkhraisha** [comment]
The prior merged PR does not fix the issue, it just shows where it is.

**Comment by OR13** [comment]
Seems to be completed, suggest closing

**Comment by mkhraisha** [comment]
Yes fixed
