### ISSUE TITLE
Get rid of `traceability/#`

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#734]
Continued from https://github.com/w3c-ccg/traceability-vocab/issues/531, the terms we are in control over should not have "slash-hashes".

**Comment by OR13** [comment]
Lots of problems remain: https://github.com/search?q=repo%3Aw3c-ccg%2Ftraceability-vocab%20traceability%2F%23&type=code

**Comment by nissimsan** [comment]
Find-replace

**Comment by OR13** [comment]
find replace in *.yaml and *.html... if it pops back up, tooling needs to be updated.

**Comment by nissimsan** [comment]
Noting that the respec anchors are still generated with /#. I still think we should fix that in the tooling.

**Comment by OR13** [comment]
@nissimsan is it possible to fix it in the same PR?

**Comment by nissimsan** [comment]
Theoretically it is, but it is a rather different topic. I would suggest keeping it separate. But let's keep this issue open to also update how the tooling generates terms which we define.
