### ISSUE TITLE
Transfer of Custody/Ownership

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-vocab#739]
On the mavennet side, we are currently using a custom [Transfer Event](https://w3c-ccg.github.io/traceability-vocab/#TransferEvent.) to track the transfers of both custody and ownership to a point in time. 
To my understanding GS1 tracks transfers of custody/ownership through a combination of a [TransactionEvent](https://ref.gs1.org/standards/epcis/), Section 7.4.4, and associating it to a [BusinessTransaction] 7.3.6.3 that outlines the transfer of custody/ownership.
A suggestion was made to track the transfers via TraceablePresentations.

We need a way to use a single approach rather than any one of the three.

**Comment by OR13** [comment]
I think we want to add some guidance on the follow:

- When should a TransferEvent VC be added to a traceable presentation?
- Should TransferEvent VC include workflow details, so it can be safely sent without integrity protection on the traceable presentation?
- When you Traceable Presentation has integrity protection?
- How should Traceable Presentation address expiration and replay attacks.

**Comment by nissimsan** [comment]
Related to the EPCIS ticket.

**Comment by nissimsan** [comment]
https://github.com/w3c-ccg/traceability-vocab/issues/385
