### ISSUE TITLE
We need CD for vocab, contexts and schemas

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-vocab#74]
#### Proposal

1. make all synthetic data generation deterministic (no randomness)
2. add a github action to commit updates to the docs folder on merges 
3. add `.gitkeep` and build steps to `postinstall` so that tests pass on first clone

#### Previous description

Faker data is working generally great for this, but we need a way to pin certain items that change based on random keys - e.g. dates.  Right now someone contributing to the repo cannot do so by only adding schema, test vectors, and credentials related to the object they are adding and have tests pass.  

We need to spend a bit of time on the test and build process and establish some good docs and policies on this.  I welcome thoughts from @OR13 and @brianwmunz as well as @mkhraisha especially.

**Comment by bumblefudge** [comment]
Definitely agree that it would be helpful to formalize/recycle some of the backchannel instructions we've had to ping Orie for.  Even the order of operations for 
1. adding schemata that reference pre-existing and immutable ontologies at dereferenceable URIs in /schemas/, then 
2 adding test-vectors for each to /test-vectors/, and finally 
3. generating full credentials made up of testable schema-defined properties and
4. adding them last to /credentials/ 
is already something helpful to formalize as guidance-- a more detailed step-by-step tutorial might be nice, either in the readme or in a separate file. 

furthermore, step 3 in the above tutorial might justify at least a paragraph of advice of the sort that Orie dishes out if asked nicely: 
3A. I would generally start with JSON-LD, get it the way you want, and then
3B. fight with JSON Schema until it generates a context that will work for you

+ It might help to link to an OS generator for making JSON Schema from target LD?

**Comment by mprorock** [comment]
> step 3 in the above tutorial might justify at least a paragraph of advice of the sort that Orie dishes out if asked nicely:
> 3A. I would generally start with JSON-LD, get it the way you want, and then
> 3B. fight with JSON Schema until it generates a context that will work for you
> 
> P.S. It might help to link to an OS generator for making JSON Schema from target LD?

yep, i think this will be a good next step.  I think this week I or someone on our side will add the ability from the generator config file to also generate credential and add that to the readme as a note for additional processing steps

**Comment by bumblefudge** [comment]
Orie also threw this together, which might be helpful for people stumbling on step 3B 😄  
https://github.com/transmute-industries/linked-data/blob/main/packages/jsonld-schema/src/jsonldToSchema.test.ts

**Comment by OR13** [comment]
yea, i think the initial solution of generators may not be scaling as well as we would like.... I have seen a couple different folks stumble on them... perhaps static json examples that re "good" and "bad" would be better / easier to maintain...

**Comment by OR13** [comment]
I think my initial implementation may have been harmful over engineering, and we may want to relax to static JSON test vectors.

**Comment by mprorock** [comment]
i am actually ok with the generator (and by and large like it).  where it gets ugly, is on dates and whatnots where test vectors outside of the new items get re-generated.  the lerna side, while cool, is what gets that build complex.  let me chew on an easier way to say: "i just added/modified this schema/these schemas, let me generate test assets, and build the intermediate file, but only modify stuff i touched"

**Comment by mprorock** [comment]
see #104 - gitignore will take care of a good chunk of this - @mkhraisha is adding in pr #103

**Comment by OR13** [comment]
I suggest we close this, and open more specific bugs in the future.

**Comment by OR13** [comment]
@mprorock that PR did not resolve this issue, it broke things... I am updating the issue description with a proposal.

**Comment by OR13** [comment]
Here is an example of how to do this, PRs welcome: https://github.com/transmute-industries/did-core/blob/main/.github/workflows/cd.yml#L32

**Comment by mprorock** [comment]
i believe this is now resolved.  there are also additional checks that will fail hard for development if you set the right env variables
