### ISSUE TITLE
merge policy

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-vocab#76]
This repo should have a clear an consistent pr and merge policy agreed upon by the editors.  

I would propose at a minimum a first review for a PR should go in within 24hrs of the PR being submitted by one of the editors.

If the changes are non breaking, limited in scope, etc then a single approval should be sufficient to merge after a 24hr delay unless an editor requests more time.  This should also apply to documentation updates that do not change project policy, release schedules, etc. that would affect the entire project.

If there is an impact beyond a single supply chain use case (as limited by commodity - e.g. steel, oil, gas) or by a cross use-case common supply chain tracking events or requirements, then more time should be automatically allocated for review prior to merge, and merge should require a majority vote (or possibly consensus?).

As we are cherry picking into releases based on stability and test passing, and in addition, keeping track of backwards compatibility issues this kind of merge policy should work well.

Requesting input from the editors: @OR13 and @mkhraisha 

Very open on this topic, but it seems like we will head off future community issues by clearly stating this policy and tying it back to the contribution requirements.  once we are agreed on a policy, (and it can be very simple).  I will doc that up and submit a PR with the document updates.

**Comment by OR13** [comment]
I think its good to formalize all this... for larger open source repos... best practices need to be enforced by CI.... but documented up front.

Regarding review time, sadly I think it must be 1 week for CCG.

**Comment by mprorock** [comment]
1 week works - I can incorporate that in

**Comment by mkhraisha** [comment]
1 week is fine, should this be incorporated into #75 ?

**Comment by mprorock** [comment]
likely will add there, or in a separate PR on top of that one

**Comment by mprorock** [comment]
added updated to #75 that should handle this for now
