### ISSUE TITLE
ISF credential fixes

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#780]
The 10+2 credential needs some updates: 
- missing bill of lading number reference
- Rename to ISF-10 (to distinguish from transit cargo requirements)
- we might want to split it up in two, according to timeliness of how data must presented
- add party identifiers!

**Comment by mkhraisha** [comment]
@nissimsan seeing that you have removed the 1.0 label can you provide an update on this issue, is this a thing that needs to be done or is it no longer valid?
