### ISSUE TITLE
Fix jsonld checker results

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#8]
https://www.jsonld-checker.com/?tab=2&repo=https%3A%2F%2Fgithub.com%2Fw3c-ccg%2Ftraceability-vocab

**Comment by OR13** [comment]
This is blocked by https://github.com/w3c-ccg/traceability-vocab/issues/7

**Comment by OR13** [comment]
unblocked... need to make sure generated examples are all passing.

**Comment by brianwmunz** [comment]
A question about this...the checker will throw a warning for new schemas because they aren't yet added to the w3id.org and the context or refs should point here.  How should this work within the testing process?

**Comment by OR13** [comment]
@brianwmunz the local tests should use the documentLoader to override the lookup like this:

https://github.com/w3c-ccg/traceability-vocab/blob/main/packages/js-vc-ci-tests/services/documentLoader.js#L19

then when the files are merged, the context here: https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/contexts/traceability-v1.jsonld

will be updated.

**Comment by mprorock** [comment]
this appears to be all resolved.
