### ISSUE TITLE
Replace https://w3id.org/traceability#Product with https://schema.org/Product

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#804]
Seems like a mistake for us to define Product.

**Comment by BenjaminMoe** [comment]
Are we asserting our Product is the same as schema.org Product? If we defined different attributed under Product then we're effectively extending it and not using it as-is.

**Comment by mkhraisha** [comment]
This has been resolved there are no references to https://w3id.org/traceability#Product
