### ISSUE TITLE
Add CredentialStatus to BankAccount VC example

### ISSUE THREAD

**Issue by adewaleafolabi** [w3c-ccg/traceability-vocab#819]
This issue is focused on updating the Bank Account Virtual Card to incorporate the 'credentialStatus' as outlined in the StatusList2021Entry specification.

**Comment by BenjaminMoe** [comment]
Is a dupe of https://github.com/w3c-ccg/traceability-vocab/issues/816?

**Comment by mkhraisha** [comment]
Closing as dupe of #816
