### ISSUE TITLE
dates should be in `YYYY-MM-DD` form

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/traceability-vocab#83]
```suggestion
      "sellByDate": "10-3-2021"
```
I don't understand how changing dates falls under fixing IRIs ... but as long as you're fixing dates, please let's use ISO standard YYYY-MM-DD across the board!  (Is the above meant to say March 10, i.e., is it DD-MM-YYYY, or October 3, i.e., is it MM-DD-YYYY?)

_Originally posted by @TallTed in https://github.com/w3c-ccg/traceability-vocab/pull/81#discussion_r573217489_

Opening a new issue, per @OR13's request.

@mprorock cited the README:

> Wherever possible, dates should be formatted as `YYYY-MM-DD` so as to be directly compatible with `xsd:date`.

**Comment by mprorock** [comment]
absolutely - as to the changes automatically, that is bc a lot of this is being generated from teh schemas being run through a generator - as we fix the generators than if fixes down the line
