### ISSUE TITLE
Fix definition for "Credential"

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#85]
We are creating confusion by defining credential... we should instead define "TraceabilityCredential" or similar... VC Data Model is responsible for defining Verifiable Credentials... not us

**Comment by mprorock** [comment]
@brianwmunz want to take this on in your next pr that is inbound?

**Comment by brianwmunz** [comment]
Makes sense. I'll take care of it.

**Comment by OR13** [comment]
amazing speed.
