### ISSUE TITLE
change requests for `workflow` property and `Workflow` class

### ISSUE THREAD

**Issue by TallTed** [w3c-ccg/traceability-vocab#852]
_Originally posted by @OR13 in https://github.com/w3c-ccg/traceability-vocab/issues/849#issuecomment-1670052391_

_Lightly edited by @TallTed for clearer issue creation_

Concrete change requests:

1. Make sure these dereference properly and that a human can read the definition when clicking them:

   - https://w3id.org/traceability#workflow-definition
   - https://w3id.org/traceability#workflow-instance

2. Remove the unused "Worklow.yml" class.

**Comment by mkhraisha** [comment]
Closing as complete
