### ISSUE TITLE
OSCAL

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#882]
Can we align any part of it with this work?

Is it relevant to evaluating our profile?

Are there policy bits that are relevant to workflows?

See also 

https://github.com/oscal-club/examples/pull/16

**Comment by aj-stein-nist** [comment]
Hi @OR13, as one of the NIST staff working on OSCAL, let me know how I can help.

**Comment by mkhraisha** [comment]
Closing based on discussion in thread.
