### ISSUE TITLE
"TraceAPI" is not a workflow actor

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#887]
Hey @rhofvendahl, I think [this](https://github.com/w3c-ccg/traceability-vocab/blob/main/docs/openapi/components/schemas/workflows/common-import-credentials.yml#L25) is a mistake. TraceAPI is not a supply chain actor.

**Comment by rhofvendahl** [comment]
@nissimsan This example is intended to illustrate credentials being passed from various parties to mesur.io's VC-API and then from there to CBP (with some addnl steps). Does that sound like a reasonable usage?

**Comment by nissimsan** [comment]
@rhofvendahl , in for example `A->>C`, I would argue that `->>` _is_ TraceAPI.

**Comment by nissimsan** [comment]
@rhofvendahl, as discussed on the call, I suggest deleting the workflow altogether. It seems in conflict with the "US CBP Entry" workflow which is the always mandatory documents required for entry filings.
