### ISSUE TITLE
Why map harvestDate, coolingDate and packingDate all to https://schema.org/endDate and lose the distinction between these?

### ISSUE THREAD

**Issue by mgh128** [w3c-ccg/traceability-vocab#892]
Referring to example 4.24 ( https://w3c-ccg.github.io/traceability-vocab/#FSMAFirstReceiverDataCredential ), the JSON-LD context resource at https://w3c-ccg.github.io/traceability-vocab/contexts/traceability-v1.jsonld 
maps all three distinct properties ( harvestDate, coolingDate, packingDate ) to https://schema.org/endDate with the result that in the Linked Data RDF triples, the credential subject has three different values for https://schema.org/endDate with no indication of the meaning of each date value.  Feel free to verify by pasting into https://json-ld.org/playground/

It surely can't be good design to lose meaning when applying a JSON-LD context resource.

It might be much better for https://github.com/w3c-ccg/ to define within its own ontology three distinct Linked Data properties for harvestDate, coolingDate, packingDate (and any other kinds of date) and to declare that each of these is considered to be a rdfs:subPropertyOf https://schema.org/endDate .  Taking this approach retains each property as a distinct property in the Linked Data / RDF triples, rather than blurring the distinction between them and having confusing multiple values for schema:endDate .

**Comment by oldskeptic** [comment]
+1 It helps if we know what ended.

**Comment by VladimirAlexiev** [comment]
Same problem as #575

**Comment by VladimirAlexiev** [comment]
@rhofvendahl Look in #575 and then #571, and you find a grep command that can find particular conflated terms:
```
grep -cr '/identifier' .|grep -vE ':(0|1)'
./common/FSMAFirstReceiverData.yml:3

grep -cr '/value' .|grep -vE ':(0|1)'
./common/FSMAAbstractKDE.yml:2
./common/IATAAirWaybill.yml:2
./common/USDAPPQ429FumigationRecord.yml:3

grep -cr '/weight' .|grep -vE ':(0|1)'
./common/ConsignmentItem.yml:2
./common/TransportEquipment.yml:2
```

**Comment by rhofvendahl** [comment]
Closed with PR 952
