### ISSUE TITLE
Allow JSON-LD Generation bypass

### ISSUE THREAD

**Issue by mprorock** [w3c-ccg/traceability-vocab#91]
We need a way to bypass generation of JSON-LD and provide manual test vectors and examples.  This will aid in resolution of #89  #88 

@Therecanbeonlyone1969 - I know this is time sensitive for your team.  Will try and get this in and documented tonight.

**Comment by mprorock** [comment]
Will need the ability to bypass code generation if JSON-LD is provided, as well as documentation on how to bypass

**Comment by Therecanbeonlyone1969** [comment]
Thanks @mprorock ... I believe we can tweak the automation I just need to dig through the js-vc code and the checker code and find where this happens. Since I did not write the code it is the needle in a haystack thing ... and it is time-sensitive for all of us, tbh.

**Comment by mprorock** [comment]
same.  I am digging as well.  I know there are some issues in [help.js](https://github.com/w3c-ccg/traceability-vocab/blob/08227323e7995164093df4a9ce5ef8cad33ea587/packages/test-vectors/src/help.js#L35) at line 35.  Other issues appear to be in the checker [here](https://github.com/w3c-ccg/traceability-vocab/blob/08227323e7995164093df4a9ce5ef8cad33ea587/packages/test-vectors/src/__tests__/linked-data-conformance.test.js#L47).  I know @OR13 is digging in also

**Comment by OR13** [comment]
to be clear, I am not working on any of these issues currently... I am helping to coordinate on them.

**Comment by mprorock** [comment]
@OR13 @Therecanbeonlyone1969 @mkhraisha any thoughts on allowing an "example_credentials" folder in docs that can store an example cred that will still have to pass credential validation, but not require full schema definitions all the way through?

These can be notated that they have not passed full integration testing from schema->ld->vc but still may serve as valid reference examples of vcs that are in the development process that apply to the traceability realm.

**Comment by Therecanbeonlyone1969** [comment]
@mprorock see my comments on #89 ... a bypass is not required despite the code issue. I found a "legal" workaround for the time being while I continue to hunt the code bugs.

**Comment by mprorock** [comment]
closing this - see #89
