### ISSUE TITLE
bad representation of `weight, volume` in `CargoItem`

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#943]
@mkhraisha @BenjaminMoe @OR13 @nissimsan 
Related to #532, these lines 

https://github.com/w3c-ccg/traceability-vocab/blob/8b5efda873a477f9f2e2b906c5099fb65363b58a/docs/openapi/components/schemas/common/CargoItem.yml#L52-L61

https://github.com/w3c-ccg/traceability-vocab/blob/8b5efda873a477f9f2e2b906c5099fb65363b58a/docs/openapi/components/schemas/common/CargoItem.yml#L69-L77

have the following problems:
- Keeping `weightUnit, volumeUnit` as separate props at the `CargoItem` level contradicts the discussion/decision in #532 to use `MeasuredValue` or `QuantitativeValue`: the unit should be inside such nodes
- `volume` says "Calculated by multiplying the width, height, and length" but there are no fields `height, length`
- `volume` is mapped to https://vocabulary.uncefact.org/grossVolumeMeasure but that's a structured node with type https://vocabulary.uncefact.org/MeasureType with fields `MeasureTypeCode` (unit), `MeasureTypeValue` (value) wheres the examples show `volume` to be a decimal.
-

**Comment by OR13** [comment]
Please raise a PR.

**Comment by VladimirAlexiev** [comment]
@OR13 , @mkhraisha 
Before anyone can make a PR, there must be agreement how to represent measurements
- a simple literal as most of them are?
  - `xsd:decimal` or `xsd:double`?
- or an intermediate node that carries `value, unit`?
  - which class & props to use? I would suggest [s:QuantitativeValue](https://schema.org/QuantitativeValue): `s:value, s:unitCode`
  - which UOM system (set of units) to use? I would suggest QUDT, eg [unit:M](https://qudt.org/vocab/unit/M), [unit:KiloGM](https://qudt.org/vocab/unit/KiloGM)

**Comment by nissimsan** [comment]
Decision here: https://github.com/w3c-ccg/traceability-vocab/issues/532#issuecomment-1589583220

**Comment by mkhraisha** [comment]
I think our final resolution is to use this layout: https://github.com/w3c-ccg/traceability-vocab/issues/532#issuecomment-1589583220

i.e we should use `xsd:decimal` and we should use QuantitativeValue
