### ISSUE TITLE
Unify to one single Address class

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#946]
_Originally posted by @OR13 in https://github.com/w3c-ccg/traceability-vocab/pull/938#discussion_r1521488783_

Addresses used by gleif do not match schema.org... so we we have multiple address formats now.

@VladimirAlexiev: 
- The best would be for Traceability to use one definition of `Address`, rather than conflicting definitions from several ontologies. This means to collect address props from all relevant ontologies.
- This pertains to the class as well (`s:address` vs `LEIaddress` mapped to https://www.gleif.org/ontology/Base/PhysicalAddress)
- The whole concept of address **lines** is obsolete when you can use newline in a string. A single field https://schema.org/streetAddress is better.

**Comment by mkhraisha** [comment]
While this is a valid concern, we cannot modify how GLEIF models their addresses and the LEI credential is controlled by GLEIF, and we are choosing to use the schema.org address as it is used everywhere else as the default. Closing as in-actionable.
