### ISSUE TITLE
Remove $linkedData

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/traceability-vocab#948]
Reasoning:

We originally developed this syntax to blend JSON-LD into JSON Schema.

We've gathered a lot of experience with this, throughout this project.

I think we have learned the following:

1. Inline JSON-Schema is better that multi file / ref based (when consuming, not necessarily when producing).

2. JSON-LD and RDF terminology design are easier to do in isolation, than when blended with YAML or JSON Schema.

3. Term definitions can be added over time, for terms that are actually useful... We don't need to generate documentation for terminology that nobody finds useful.

I'd like to propose we simplify the vocabulary, and modularize it, and remove the polyglotting which probably makes contribution and review very difficult for experts.

**Comment by VladimirAlexiev** [comment]
@OR13 
While editing GLEI schemas, I found it difficult to fix problems because there's a lot of repetition of examples.
So making editing more modular is a worthy goal.
But then what editorial procedures to use for binding to Linked Data?

**Comment by OR13** [comment]
Perhaps the answer should be a context per credential type.

**Comment by mkhraisha** [comment]
While this is a great suggestion, this would be a good v2 project, and not something anyone is willing to undertake at current time.
