### ISSUE TITLE
conflation of `weight`

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-ccg/traceability-vocab#953]
Check done on 12 Mar 2024:
```
grep -cr '/weight' .|grep -vE ':(0|1)'
./common/ConsignmentItem.yml:2
./common/TransportEquipment.yml:2
```

Same problem as  https://github.com/w3c-ccg/traceability-vocab/issues/575,  https://github.com/w3c-ccg/traceability-vocab/issues/571, #892

**Comment by nissimsan** [comment]
See #571 for details
